// The reaction picker's search set (src/components/Reactions.tsx). The app
// has no emoji dataset, so this is a small built-in one: common emojis with
// English search words, a few French ones where the word differs. The quick
// row (shared/reactions.ts QUICK_REACTIONS) comes first in it.
export interface EmojiEntry {
  emoji: string;
  words: string;
}

export const EMOJI_LIST: readonly EmojiEntry[] = [
  { emoji: "👍", words: "thumbs up yes ok agree like +1 pouce" },
  { emoji: "❤️", words: "heart love red coeur amour" },
  { emoji: "😂", words: "joy laugh tears funny lol rire" },
  { emoji: "🎉", words: "party tada celebrate congrats fete bravo" },
  { emoji: "👀", words: "eyes look looking watching yeux regarde" },
  { emoji: "🙏", words: "pray thanks please hope merci" },
  { emoji: "✅", words: "check done yes complete fait" },
  { emoji: "❌", words: "cross no wrong cancel non" },
  { emoji: "👎", words: "thumbs down no dislike -1" },
  { emoji: "👏", words: "clap applause bravo" },
  { emoji: "🙌", words: "raised hands hooray celebrate" },
  { emoji: "👌", words: "ok perfect fine parfait" },
  { emoji: "✌️", words: "victory peace" },
  { emoji: "🤞", words: "fingers crossed luck hope" },
  { emoji: "💪", words: "strong muscle flex force" },
  { emoji: "👋", words: "wave hello hi bye bonjour salut" },
  { emoji: "🤝", words: "handshake deal agree accord" },
  { emoji: "🫡", words: "salute yes sir roger" },
  { emoji: "🙂", words: "smile slight happy sourire" },
  { emoji: "😀", words: "grin happy smile" },
  { emoji: "😄", words: "smile happy joy" },
  { emoji: "😁", words: "beam grin happy" },
  { emoji: "😅", words: "sweat smile relief phew" },
  { emoji: "🤣", words: "rofl laugh rolling funny" },
  { emoji: "😊", words: "blush smile happy" },
  { emoji: "😇", words: "angel innocent halo" },
  { emoji: "😉", words: "wink" },
  { emoji: "😍", words: "heart eyes love adore" },
  { emoji: "🥰", words: "love hearts adore" },
  { emoji: "😘", words: "kiss love bisou" },
  { emoji: "😋", words: "yum tasty delicious" },
  { emoji: "😎", words: "cool sunglasses" },
  { emoji: "🤓", words: "nerd geek" },
  { emoji: "🤩", words: "star struck wow amazing" },
  { emoji: "🥳", words: "party celebrate birthday" },
  { emoji: "😏", words: "smirk" },
  { emoji: "😌", words: "relieved calm" },
  { emoji: "🤔", words: "thinking hmm think question" },
  { emoji: "🤨", words: "raised eyebrow skeptical doubt" },
  { emoji: "😐", words: "neutral meh" },
  { emoji: "😑", words: "expressionless meh" },
  { emoji: "😶", words: "no mouth silent speechless" },
  { emoji: "🙄", words: "eye roll whatever" },
  { emoji: "😬", words: "grimace awkward oops" },
  { emoji: "🤐", words: "zipper secret quiet" },
  { emoji: "🤫", words: "shush quiet secret" },
  { emoji: "🤭", words: "oops giggle hand over mouth" },
  { emoji: "🫠", words: "melting embarrassed" },
  { emoji: "😴", words: "sleep tired zzz dodo" },
  { emoji: "🥱", words: "yawn tired bored" },
  { emoji: "😪", words: "sleepy tired" },
  { emoji: "😮", words: "open mouth surprise wow" },
  { emoji: "😯", words: "hushed surprise" },
  { emoji: "😲", words: "astonished shock wow" },
  { emoji: "🤯", words: "mind blown exploding wow" },
  { emoji: "😳", words: "flushed embarrassed" },
  { emoji: "🥺", words: "pleading puppy eyes please" },
  { emoji: "😢", words: "cry sad tear triste" },
  { emoji: "😭", words: "sob cry sad" },
  { emoji: "😞", words: "disappointed sad" },
  { emoji: "😔", words: "pensive sad" },
  { emoji: "😟", words: "worried concern" },
  { emoji: "😕", words: "confused" },
  { emoji: "🙃", words: "upside down silly irony" },
  { emoji: "😤", words: "triumph huff frustrated" },
  { emoji: "😠", words: "angry mad" },
  { emoji: "😡", words: "rage angry mad colere" },
  { emoji: "🤬", words: "cursing swear angry" },
  { emoji: "😱", words: "scream fear shock" },
  { emoji: "😨", words: "fearful scared" },
  { emoji: "😰", words: "anxious sweat nervous" },
  { emoji: "🤗", words: "hug hugging" },
  { emoji: "🤒", words: "sick ill thermometer malade" },
  { emoji: "🤢", words: "nauseated sick gross" },
  { emoji: "🤧", words: "sneeze sick cold" },
  { emoji: "🤠", words: "cowboy" },
  { emoji: "🤡", words: "clown" },
  { emoji: "💀", words: "skull dead dying lol" },
  { emoji: "👻", words: "ghost boo" },
  { emoji: "👽", words: "alien" },
  { emoji: "🤖", words: "robot bot" },
  { emoji: "💩", words: "poop" },
  { emoji: "🔥", words: "fire hot lit feu" },
  { emoji: "✨", words: "sparkles shiny magic new" },
  { emoji: "⭐", words: "star favorite etoile" },
  { emoji: "🌟", words: "glowing star" },
  { emoji: "💯", words: "hundred perfect 100" },
  { emoji: "💥", words: "boom collision" },
  { emoji: "💡", words: "idea light bulb idee" },
  { emoji: "🚀", words: "rocket ship launch deploy fusee" },
  { emoji: "⚡", words: "lightning zap fast" },
  { emoji: "🎯", words: "target bullseye goal" },
  { emoji: "🏆", words: "trophy win winner" },
  { emoji: "🥇", words: "gold medal first" },
  { emoji: "🎁", words: "gift present cadeau" },
  { emoji: "🎂", words: "birthday cake gateau" },
  { emoji: "🍕", words: "pizza" },
  { emoji: "🍔", words: "burger" },
  { emoji: "☕", words: "coffee cafe" },
  { emoji: "🍺", words: "beer biere" },
  { emoji: "🍻", words: "cheers beers" },
  { emoji: "🥂", words: "cheers champagne" },
  { emoji: "🍿", words: "popcorn" },
  { emoji: "💔", words: "broken heart" },
  { emoji: "🧡", words: "orange heart" },
  { emoji: "💛", words: "yellow heart" },
  { emoji: "💚", words: "green heart" },
  { emoji: "💙", words: "blue heart" },
  { emoji: "💜", words: "purple heart" },
  { emoji: "🖤", words: "black heart" },
  { emoji: "🤍", words: "white heart" },
  { emoji: "💖", words: "sparkling heart" },
  { emoji: "💬", words: "speech bubble comment" },
  { emoji: "💭", words: "thought bubble" },
  { emoji: "❓", words: "question" },
  { emoji: "❗", words: "exclamation important" },
  { emoji: "⚠️", words: "warning caution attention" },
  { emoji: "🚫", words: "prohibited no forbidden" },
  { emoji: "⛔", words: "no entry stop" },
  { emoji: "🛑", words: "stop sign" },
  { emoji: "☑️", words: "check box ballot done" },
  { emoji: "✔️", words: "check mark done" },
  { emoji: "➕", words: "plus add" },
  { emoji: "➖", words: "minus remove" },
  { emoji: "🔁", words: "repeat retry again" },
  { emoji: "⏳", words: "hourglass waiting pending" },
  { emoji: "⏰", words: "alarm clock time" },
  { emoji: "📌", words: "pin pushpin" },
  { emoji: "📎", words: "paperclip attachment" },
  { emoji: "📝", words: "memo note write" },
  { emoji: "📅", words: "calendar date" },
  { emoji: "📈", words: "chart up growth" },
  { emoji: "📉", words: "chart down decline" },
  { emoji: "📣", words: "megaphone announce" },
  { emoji: "🔔", words: "bell notification" },
  { emoji: "🔒", words: "lock secure" },
  { emoji: "🔑", words: "key" },
  { emoji: "🔧", words: "wrench fix tool" },
  { emoji: "🛠️", words: "tools build fix" },
  { emoji: "🐛", words: "bug" },
  { emoji: "🧪", words: "test tube experiment" },
  { emoji: "💻", words: "laptop computer" },
  { emoji: "📦", words: "package box ship" },
  { emoji: "🧠", words: "brain smart" },
  { emoji: "👑", words: "crown king queen" },
  { emoji: "🌈", words: "rainbow" },
  { emoji: "☀️", words: "sun sunny soleil" },
  { emoji: "🌙", words: "moon night lune" },
  { emoji: "❄️", words: "snow cold neige" },
  { emoji: "🌧️", words: "rain pluie" },
  { emoji: "🌱", words: "seedling grow plant" },
  { emoji: "🍀", words: "clover luck" },
  { emoji: "🌹", words: "rose flower fleur" },
  { emoji: "🐶", words: "dog chien" },
  { emoji: "🐱", words: "cat chat" },
  { emoji: "🦉", words: "owl hibou" },
  { emoji: "🐢", words: "turtle slow" },
  { emoji: "🦄", words: "unicorn" },
  { emoji: "🐐", words: "goat best" },
  { emoji: "🇨🇦", words: "canada flag drapeau" },
  { emoji: "🇫🇷", words: "france flag drapeau" },
  { emoji: "🇧🇷", words: "brazil brasil flag" },
  { emoji: "🇺🇸", words: "usa united states flag" },
];

function plain(text: string): string {
  return text.normalize("NFD").replace(/\p{M}/gu, "").toLowerCase().trim();
}

/** The entries whose words start with every word of the query, in list
 * order; the whole list for an empty query. An emoji typed or pasted as
 * the query finds itself. */
export function searchEmoji(query: string, limit = 48): EmojiEntry[] {
  const terms = plain(query).split(/\s+/).filter(Boolean);
  if (!terms.length) return EMOJI_LIST.slice(0, limit);
  const out: EmojiEntry[] = [];
  for (const entry of EMOJI_LIST) {
    if (entry.emoji === query.trim()) {
      out.unshift(entry);
      continue;
    }
    const words = plain(entry.words).split(/\s+/);
    if (terms.every((term) => words.some((word) => word.startsWith(term)))) out.push(entry);
    if (out.length >= limit) break;
  }
  return out;
}
