package com.openmausbot.companion.ui

import androidx.compose.runtime.Composable
import androidx.compose.ui.res.stringResource
import com.openmausbot.companion.R

/** Translates fixed English copy returned by UI policy helpers. */
private val localizedCopyResources = mapOf(
    "Threads list" to R.string.mobile_threads_list,
    "List density" to R.string.mobile_list_density,
    "Change list density" to R.string.mobile_change_list_density,
    "Comfortable" to R.string.mobile_density_comfortable,
    "Compact" to R.string.mobile_density_compact,
    "Larger faces, with each bot's latest message under its name." to R.string.mobile_density_comfortable_caption,
    "One line per bot. Bots with more than one active thread show how many; tap the number to list them." to R.string.mobile_density_compact_caption,
    "%1\$d active" to R.string.mobile_updates_active_count,
    "%1\$d links" to R.string.mobile_share_links,
    "%1\$d messages queued" to R.string.mobile_updates_queued_count,
    "%1\$d more updates" to R.string.mobile_updates_more_count,
    "%1\$d text items" to R.string.mobile_share_text_items,
    "%1\$d unsupported items were left out." to R.string.mobile_share_items_omitted,
    "%1\$s at %2\$s" to R.string.mobile_routine_daily_at,
    "%1\$s avatar" to R.string.mobile_current_name_avatar_de638954,
    "%1\$s folder" to R.string.mobile_a11y_folder,
    "%1\$s has a question" to R.string.mobile_chat_name_has_a_question_13ca9f26,
    "%1\$s has an update" to R.string.mobile_updates_headline_review,
    "%1\$s is larger than %2\$d MB." to R.string.mobile_share_too_large,
    "%1\$s is larger than the %2\$s remaining attachment limit." to R.string.mobile_attachment_too_large,
    "%1\$s is ready" to R.string.mobile_section_ready,
    "%1\$s is working" to R.string.mobile_updates_headline_working,
    "%1\$s isn't a supported attachment. Try an image, PDF, text, Word, Excel, or PowerPoint file." to R.string.mobile_chat_attachment_unsupported,
    "%1\$s isn't a supported document. Try PDF, text, Word, Excel, or PowerPoint." to R.string.mobile_share_unsupported_document,
    "%1\$s lines added, %2\$s removed" to R.string.mobile_a11y_diff_stats,
    "%1\$s minutes" to R.string.mobile_minutes_minutes_29dd88a9,
    "%1\$s needs you" to R.string.mobile_updates_headline_needs_you,
    "%1\$s · %2\$s" to R.string.mobile_routine_run_subtitle,
    "%1\$s · %2\$s · %3\$s" to R.string.mobile_routine_subtitle,
    "%1\$s · connected" to R.string.mobile_roster_header_connected,
    "%1\$s · connecting…" to R.string.mobile_roster_header_connecting,
    "%1\$s · offline" to R.string.mobile_roster_header_offline,
    "%1\$s · starting %2\$s" to R.string.mobile_routine_interval_with_start,
    "%1\$s · unpaired" to R.string.mobile_roster_header_unpaired,
    "%1\$s's computer" to R.string.mobile_bot_name_s_computer_7637def1,
    "%1\$s's current model doesn't support images. Choose another bot or share without the image." to R.string.mobile_share_bot_image_compatibility,
    "%1\$s. The copied diff always includes every line" to R.string.mobile_a11y_diff_copy_hint,
    ", " to R.string.mobile_routine_weekday_separator,
    "/computer" to R.string.mobile_computer_458a0ead,
    "/diff" to R.string.mobile_diff_c1ee9024,
    "/retry" to R.string.mobile_retry_cdc02b83,
    "/steer" to R.string.mobile_steer_72f3f4c7,
    "/threads" to R.string.mobile_threads_3e761c97,
    "000000" to R.string.mobile_text_c984aed0,
    "1 more update" to R.string.mobile_updates_one_more,
    "1 step" to R.string.mobile_step_29869c51,
    "1 unsupported item was left out." to R.string.mobile_share_one_item_omitted,
    "1.  Open OpenMausBot → Settings → Phone" to R.string.mobile_open_openmausbot_settings_phone_38cfc5bb,
    "100 selected — that’s the section limit." to R.string.mobile_section_at_limit,
    "2.  Choose Set up a phone" to R.string.mobile_choose_set_up_a_phone_8fd474a9,
    "6-digit or ABCD-EFGH-JKLM code" to R.string.mobile_pairing_code_placeholder,
    "A frame of this bot's computer" to R.string.mobile_a_frame_of_this_bot_s_computer_39b6a5bb,
    "A section can have one Chief. Go back and choose one Chief, or use a section without one." to R.string.mobile_section_chief_conflict,
    "Account alias" to R.string.mobile_account_alias_8cf27ca0,
    "Account details are unavailable from this provider. Refresh after authorization finishes." to R.string.mobile_account_details_are_unavailable_fr_d9d62172,
    "Accounts could not be re-checked" to R.string.mobile_accounts_could_not_be_re_checked_6727be8f,
    "Actions for %1\$s" to R.string.mobile_actions_for_routine_name_767f1549,
    "Active" to R.string.mobile_active_a733b809,
    "Activity" to R.string.mobile_settings_activity_label,
    "Activity detail" to R.string.mobile_activity_detail_049f3bdf,
    "Add" to R.string.mobile_add_61cc55aa,
    "Add a document from Files" to R.string.mobile_action_add_document,
    "Add a photo to this message" to R.string.mobile_action_add_photo,
    "Add another account" to R.string.mobile_add_another_account_5dcc7913,
    "Add the address of your Chatterbox server in OpenMausBot on the computer to turn speech back on." to R.string.mobile_profile_chatterbox_voice_unconfigured_footer,
    "Add the shared ElevenLabs key in this agent's profile on the computer. The key is never returned to this phone." to R.string.mobile_profile_voice_unconfigured_footer,
    "Add the shared Fish Audio API key in OpenMausBot on the computer. The key is never returned to this phone." to R.string.mobile_profile_fish_voice_unconfigured_footer,
    "Address" to R.string.mobile_address_d70f93df,
    "Adds to existing section" to R.string.mobile_adds_to_existing_section_731f1f94,
    "Advanced" to R.string.mobile_advanced_4d064726,
    "Agent" to R.string.mobile_agent_5ce2e6f4,
    "Agent notifications" to R.string.mobile_agent_notifications_a3bd8bd0,
    "Alignment time" to R.string.mobile_alignment_time_ca919bd7,
    "All quiet" to R.string.mobile_all_quiet_889fd4f7,
    "Allow camera access to scan the pairing QR code shown by OpenMausBot, or go back and enter the address and code by hand." to R.string.mobile_camera_permission_denied,
    "Allow camera access to scan the pairing QR code shown by OpenMausBot." to R.string.mobile_camera_permission_description,
    "Allow once" to R.string.mobile_allow_once_c551e6cf,
    "Allowed" to R.string.mobile_settings_notifications_allowed,
    "Always allow" to R.string.mobile_always_allow_41325daa,
    "Always allow this tool" to R.string.mobile_always_allow_this_tool_2ce82a7e,
    "Always on" to R.string.mobile_settings_always_on,
    "An alias makes the account explicit when an agent uses more than one %1\$s account." to R.string.mobile_an_alias_makes_the_account_explici_725873b3,
    "Answered" to R.string.mobile_answered_e0aafffa,
    "API keys, pairing and the Local VM are managed on the computer. This phone is deliberately not allowed to change them." to R.string.mobile_settings_not_here_body,
    "Apply model" to R.string.mobile_apply_model_474897c3,
    "Approvals and finished work appear while OpenMausMobile is connected, including frames replayed after a short background pause. Closed-app push needs a separate push-relay release that does not exist yet." to R.string.mobile_settings_notifications_footer,
    "Approvals and questions" to R.string.notification_channel_blocking,
    "Approvals that are waiting for you" to R.string.mobile_onboarding_notifications_approvals,
    "Archive" to R.string.mobile_a11y_archive,
    "Archived" to R.string.mobile_archived_eddc813f,
    "Art direction" to R.string.mobile_art_direction_52d878a2,
    "Ask %1\$s" to R.string.mobile_composer_ask_bot,
    "Automatic" to R.string.mobile_share_route_automatic,
    "Avatar" to R.string.mobile_avatar_7631b26e,
    "Back" to R.string.mobile_back_b52b36b7,
    "Bot" to R.string.mobile_share_bot,
    "Bot messages" to R.string.notification_channel_done,
    "Bot settings" to R.string.mobile_bot_settings_7092a294,
    "Bot threads" to R.string.mobile_bot_threads_ec81acf2,
    "Bot · %1\$s" to R.string.mobile_share_bot_thread,
    "Bots" to R.string.mobile_bots_4ca88ea4,
    "Bots you create on your computer show up here." to R.string.mobile_roster_empty_description,
    "Camera access needed" to R.string.mobile_camera_access_needed_28a22fc4,
    "Can reach" to R.string.mobile_can_reach_e5d301f8,
    "Cancel" to R.string.mobile_cancel_77dfd213,
    "Change activity detail" to R.string.mobile_settings_change_activity_detail,
    "Change when the interval starts" to R.string.mobile_a11y_change_interval_start,
    "Channel" to R.string.mobile_share_channel,
    "Channel · %1\$s" to R.string.mobile_share_channel_thread,
    "Chat" to R.string.mobile_settings_chat_section,
    "Checking Cloud VM availability…" to R.string.mobile_checking_cloud_vm_availability_b07ff23f,
    "Choose a bot or channel" to R.string.mobile_choose_a_bot_or_channel_da2a8cc1,
    "Choose a computer" to R.string.mobile_choose_a_computer_f361ffc3,
    "Choose a different computer" to R.string.mobile_choose_a_different_computer_9e2a62ed,
    "Choose a PNG, JPEG, GIF, or WebP image." to R.string.mobile_choose_a_png_jpeg_gif_or_webp_image_1f68957d,
    "Choose a repeat interval" to R.string.mobile_choose_a_repeat_interval_f59b3f71,
    "Choose all that apply" to R.string.mobile_choose_all_that_apply_5a20d235,
    "Choose an agent" to R.string.mobile_choose_an_agent_faaaf2b4,
    "Choose an agent voice" to R.string.mobile_choose_an_agent_voice_e284a527,
    "Choose an available provider to change this bot's model." to R.string.mobile_model_unavailable_note,
    "Choose File" to R.string.mobile_choose_file_54a2a841,
    "Choose more bots for another section, or tap Done." to R.string.mobile_section_add_more_bots,
    "Choose up to 100 bots for one section." to R.string.mobile_section_under_limit,
    "Choose where this should go" to R.string.mobile_share_choose_destination,
    "Circle" to R.string.mobile_circle_1cc7820a,
    "Clear search" to R.string.mobile_clear_search_67300d0f,
    "Close" to R.string.mobile_a11y_close,
    "Close slash commands" to R.string.mobile_close_slash_commands_5ff49abb,
    "Closed" to R.string.mobile_thread_closed,
    "Cloud VM" to R.string.mobile_cloud_vm_26ca291f,
    "Cloud VM status is unavailable" to R.string.mobile_cloud_vm_status_is_unavailable_32c78491,
    "Collapse" to R.string.mobile_collapse_9cf188d3,
    "Collapsed, %1\$s threads" to R.string.mobile_a11y_thread_state_collapsed,
    "Collapsed" to R.string.mobile_a11y_collapsed,
    "Completed" to R.string.mobile_completed_1798b3ba,
    "Completed, waiting, failed, and manually started runs appear here." to R.string.mobile_completed_waiting_failed_and_manually_st_55acdcb1,
    "COMPUTER" to R.string.mobile_computer_9e47da19,
    "Computer" to R.string.mobile_computer_924645b3,
    "computer" to R.string.mobile_computer_c60266a8,
    "Computer only" to R.string.mobile_computer_only_bc8646ec,
    "Configure Composio on your computer first. Provider credentials are never returned to this phone." to R.string.mobile_configure_composio_on_your_compute_4281e8b0,
    "Confirm computer" to R.string.mobile_confirm_computer_d778cfbd,
    "Connect" to R.string.mobile_connect_b65463cb,
    "Connect %1\$s" to R.string.mobile_connect_card_label_c9e612b4,
    "Connect a computer" to R.string.mobile_settings_connect_computer,
    "Connect another computer" to R.string.mobile_settings_connect_another_computer,
    "Connect computer" to R.string.mobile_onboarding_connect_computer,
    "Connect my computer" to R.string.mobile_onboarding_welcome_connect,
    "Connect when you're ready" to R.string.mobile_onboarding_unpaired_title,
    "Connected Apps" to R.string.mobile_connected_apps_8ab72a8e,
    "Connected apps need setup" to R.string.mobile_connected_apps_need_setup_2cdb536a,
    "Connection" to R.string.mobile_settings_connection_label,
    "Connection unknown" to R.string.mobile_connection_unknown_973b0484,
    "Continue" to R.string.mobile_continue_2e026239,
    "Copied" to R.string.mobile_copied_8e3df45a,
    "Copy" to R.string.mobile_copy_af74f7c5,
    "Copy all" to R.string.mobile_copy_all_9da9f044,
    "Copy CSV" to R.string.mobile_copy_csv_b810b7cd,
    "Copy Diff" to R.string.mobile_copy_diff_18f2296a,
    "Could not open the cloud desktop." to R.string.mobile_cloud_desktop_open_failed,
    "Couldn't add that attachment." to R.string.mobile_chat_add_attachment_failed,
    "Couldn't create this thread. Try again." to R.string.mobile_chat_create_thread_failed,
    "Couldn't open that file. Try again." to R.string.mobile_chat_open_file_failed,
    "Couldn't reach %1\$s. Keep OpenMausBot open and Phone access on, then try again." to R.string.mobile_share_offline,
    "Couldn't send this message. Try again." to R.string.mobile_chat_send_failed,
    "Couldn't start the microphone." to R.string.mobile_couldn_t_start_the_microphone_320ceafa,
    "Couldn't transcribe that." to R.string.mobile_couldn_t_transcribe_that_f440f144,
    "Couldn't update this thread. Try again." to R.string.mobile_chat_thread_update_failed,
    "Create" to R.string.mobile_create_6e157c5d,
    "Creates a new section" to R.string.mobile_creates_a_new_section_9da73eb0,
    "Current agent voice" to R.string.mobile_current_agent_voice_4e95cc5f,
    "Current provider (unavailable)" to R.string.mobile_current_provider_unavailable_2fe5cf65,
    "Custom" to R.string.mobile_custom_081ae3fd,
    "Custom interval" to R.string.mobile_custom_interval_1eea7679,
    "DATA TABLE" to R.string.mobile_data_table_54baf78e,
    "Default" to R.string.mobile_default_808d7dca,
    "Delete" to R.string.mobile_delete_f6fdbe48,
    "Delete %1\$s" to R.string.mobile_delete_taskrules_title_task_961ae881,
    "Delete routine" to R.string.mobile_delete_routine_0cb076a0,
    "Delete this queued message" to R.string.mobile_delete_this_queued_message_4390e043,
    "Deleted agent" to R.string.mobile_deleted_agent_ff6eff9d,
    "Deny" to R.string.mobile_deny_53577bb5,
    "Dictation isn't available for this language." to R.string.mobile_dictation_isn_t_available_for_this_langu_1a6b15c5,
    "Dictation needs Microphone access. Enable it in Settings → OpenMausMobile." to R.string.mobile_dictation_needs_microphone_access_enable_e9addded,
    "Dismiss" to R.string.mobile_dismiss_70afe9ef,
    "Does" to R.string.mobile_does_0ae736c9,
    "Done" to R.string.mobile_done_e9b450d1,
    "Each computer is paired separately. Only the selected computer is active at a time." to R.string.mobile_settings_computers_paired_separately,
    "Edit" to R.string.mobile_edit_5301648d,
    "Edit address" to R.string.mobile_edit_address_31fe67f4,
    "Edit and retry" to R.string.mobile_edit_and_retry_f683a3c2,
    "Edit quick reply" to R.string.mobile_edit_quick_reply_57e333e3,
    "Edit routine" to R.string.mobile_edit_routine_6e36897b,
    "Edit, reorder, or remove the prompts shown above an empty composer." to R.string.mobile_edit_reorder_or_remove_the_prompts_1044e38d,
    "ElevenLabs is not configured" to R.string.mobile_profile_elevenlabs_unconfigured,
    "Enter a secure https:// address, 192.168.1.42:8810, or a name like macbook.tail1234.ts.net." to R.string.mobile_settings_invalid_address,
    "Enter the 6-digit code shown on your desktop:" to R.string.mobile_pairing_enter_code_notice,
    "Enter whatever Phone settings on your computer shows. The pairing itself is kept." to R.string.mobile_settings_edit_address_message,
    "Every %1\$d min" to R.string.mobile_routine_every_minutes,
    "Every bot that may answer in this channel must use a model that supports images." to R.string.mobile_share_channel_image_compatibility,
    "Every day" to R.string.mobile_every_day_3b2eb513,
    "Every step a bot takes." to R.string.mobile_activity_full_caption,
    "Every X minutes" to R.string.mobile_every_x_minutes_000b5c3a,
    "Expand" to R.string.mobile_expand_9869e506,
    "Expanded, %1\$s threads" to R.string.mobile_a11y_thread_state_expanded,
    "Expanded" to R.string.mobile_a11y_expanded,
    "Explain steps" to R.string.mobile_explain_steps_b60a9fb6,
    "FILE" to R.string.mobile_file_b4915d3a,
    "File" to R.string.mobile_file_2c3cafa4,
    "File attachment: %1\$s. Tap to preview." to R.string.mobile_a11y_file_attachment,
    "Finished work and important updates" to R.string.mobile_onboarding_notifications_finished,
    "Fish Audio" to R.string.mobile_fish_audio_d3c00ff4,
    "Fish Audio is not configured" to R.string.mobile_profile_fish_unconfigured,
    "For example: summarize this and list the next steps" to R.string.mobile_for_example_summarize_this_and_lis_12b3d099,
    "Fri" to R.string.mobile_routine_friday_short,
    "Friday" to R.string.mobile_routine_friday,
    "From 5 minutes to 24 hours" to R.string.mobile_from_5_minutes_to_24_hours_a6bafa40,
    "Full" to R.string.mobile_activity_full,
    "Generate an avatar" to R.string.mobile_generate_an_avatar_01e5cee4,
    "Generate on computer" to R.string.mobile_generate_on_computer_ff5b7448,
    "Generation uses the shared image provider configured on your computer. No provider key is sent to or stored on this phone." to R.string.mobile_profile_generate_ready,
    "Group name (optional)" to R.string.mobile_group_name_optional_0fd3a15c,
    "Groups" to R.string.mobile_groups_ae9629f4,
    "Hidden" to R.string.mobile_activity_hidden,
    "Hide" to R.string.mobile_hide_34d8b60f,
    "Hide Diff" to R.string.mobile_hide_diff_120df7c2,
    "Hide full address" to R.string.mobile_hide_full_address_63c5e519,
    "https://mac.example or 192.168.1.42:8810" to R.string.mobile_https_mac_example_or_192_168_1_42__e277eb2d,
    "Icon" to R.string.mobile_icon_716f63b9,
    "Identity" to R.string.mobile_identity_7e5a975b,
    "Idle" to R.string.mobile_idle_cc1ebdd0,
    "If it never appears, install Tailscale on both and sign in to the same account — Phone settings will then show a name ending in .ts.net to enter below." to R.string.mobile_pair_tailscale_hint,
    "Image" to R.string.mobile_image_50e19fda,
    "Image attachment: %1\$s. Tap to preview." to R.string.mobile_a11y_image_attachment,
    "Image unavailable" to R.string.mobile_image_unavailable,
    "Inspect latest git changes and patches" to R.string.mobile_slash_diff_description,
    "Instruction (optional)" to R.string.mobile_instruction_optional_3c5a084f,
    "Interrupt" to R.string.mobile_interrupt_d5db4549,
    "Interval unavailable" to R.string.mobile_routine_interval_unavailable,
    "It was removed from the computer's Phone settings, or the pairing was reset." to R.string.mobile_pairing_removed_reason,
    "Keep the optional instruction under 20,000 characters." to R.string.mobile_share_instruction_limit,
    "Label" to R.string.mobile_label_74341e3c,
    "LAST USED" to R.string.mobile_last_used_ac909777,
    "Link" to R.string.mobile_share_link,
    "Listening…" to R.string.mobile_listening_6c19a476,
    "Live view of what %1\$s is doing" to R.string.mobile_action_live_computer,
    "Load earlier messages" to R.string.mobile_load_earlier_messages_4ac08d16,
    "Loading models" to R.string.mobile_loading_models_eeade2be,
    "Local discovery was interrupted. Retrying…" to R.string.mobile_local_discovery_was_interrupted_retrying_4f231b2f,
    "Local network" to R.string.mobile_share_route_local_network,
    "Looking…" to R.string.mobile_looking_5e65f10e,
    "Manage %1\$s's threads" to R.string.mobile_manage_bot_name_s_threads_f3530e9f,
    "Mascot" to R.string.mobile_mascot_e0489488,
    "MausBot is staying connected" to R.string.always_on_notification_title,
    "Message" to R.string.mobile_message_68f4145f,
    "Messaged %1\$s" to R.string.mobile_messaged_it_withname_bd9371e7,
    "Messages" to R.string.mobile_roster_messages,
    "minutes" to R.string.mobile_minutes_be2e2bb6,
    "minutes, starting" to R.string.mobile_minutes_starting_288a3d24,
    "Model" to R.string.mobile_model_68c2cc7f,
    "Model, profile, voice and notifications" to R.string.mobile_action_bot_settings,
    "Mon" to R.string.mobile_routine_monday_short,
    "Monday" to R.string.mobile_routine_monday,
    "More" to R.string.mobile_more_4bab2d8f,
    "Move down" to R.string.mobile_move_down_260ff8ae,
    "Move up" to R.string.mobile_move_up_b4f57cd0,
    "Needs attention" to R.string.mobile_roster_needs_attention,
    "Needs you" to R.string.mobile_needs_you_0d9d0df1,
    "Needs your attention" to R.string.mobile_share_needs_attention,
    "New bot" to R.string.mobile_new_bot_66d3c052,
    "New group" to R.string.mobile_new_group_f9850c0b,
    "New quick reply" to R.string.mobile_new_quick_reply_c5c6238d,
    "New routine" to R.string.mobile_new_routine_32809dc6,
    "New task" to R.string.mobile_new_task_17b2b838,
    "New thread" to R.string.mobile_new_thread_02057e28,
    "New thread with %1\$s" to R.string.mobile_new_thread_with_bot_name_80fb4510,
    "Next" to R.string.mobile_next_bc981983,
    "Next version" to R.string.mobile_next_version_514439d0,
    "No activity, only messages." to R.string.mobile_activity_hidden_caption,
    "No app on this phone can open %1\$s." to R.string.mobile_file_no_viewer,
    "No app on this phone can share %1\$s." to R.string.mobile_file_no_share_app,
    "No bots yet" to R.string.mobile_roster_no_bots_yet,
    "No changes recorded yet." to R.string.mobile_no_changes_recorded_yet_2eab95e9,
    "No connected apps are available from this computer." to R.string.mobile_no_connected_apps_are_available_fr_0529e71d,
    "No limit" to R.string.mobile_no_limit_10850b93,
    "No model providers are available" to R.string.mobile_model_none_available,
    "No routines" to R.string.mobile_no_routines_1cd3f572,
    "No thread matches “%1\$s”." to R.string.mobile_roster_no_thread_matches,
    "No workspace default voice is selected. Choose an agent-specific voice above; synthesis still uses Fish Audio on your computer." to R.string.mobile_profile_fish_no_default_footer,
    "No workspace default voice is selected. Choose an agent-specific voice above; synthesis still uses the shared ElevenLabs key on your computer." to R.string.mobile_profile_elevenlabs_no_default_footer,
    "No workspace default voice is selected. Choose an agent-specific voice above; synthesis still uses your Chatterbox server." to R.string.mobile_profile_chatterbox_no_default_footer,
    "No workspace default voice is selected. Choose an agent-specific voice above; synthesis still uses your computer's built-in voices." to R.string.mobile_profile_system_no_default_footer,
    "Not allowed" to R.string.mobile_settings_notifications_not_allowed,
    "Not here" to R.string.mobile_settings_not_here,
    "Not now" to R.string.mobile_onboarding_not_now,
    "Not paired" to R.string.mobile_settings_not_paired_status,
    "Nothing found yet. Check that this phone and your computer are on the same Wi-Fi network — a guest network often blocks them from seeing each other. You can always enter the address below instead." to R.string.mobile_pair_discovery_empty,
    "Nothing matches" to R.string.mobile_roster_nothing_matches,
    "Nothing needs you" to R.string.mobile_nothing_needs_you_c7649c9b,
    "Nothing scheduled or learned yet." to R.string.mobile_nothing_scheduled_or_learned_yet_a497b19f,
    "Nothing to show yet" to R.string.mobile_nothing_to_show_yet_95f8d609,
    "Notifications" to R.string.mobile_settings_notifications_section,
    "Notifications are on" to R.string.mobile_settings_notifications_on,
    "Notifications only arrive while the app is open or was recently backgrounded. Turn this on if you rely on scheduled routines to notify you later — it adds a permanent low-priority notification and uses a little more battery." to R.string.mobile_settings_background_off_description,
    "Notifications will reach you even with the app closed" to R.string.always_on_notification_text,
    "OK" to R.string.mobile_ok_9ce3bd42,
    "On this network" to R.string.mobile_on_this_network_4c9f524a,
    "On your computer" to R.string.mobile_on_your_computer_9a621537,
    "On your computer, open OpenMausBot → Settings → Phone." to R.string.mobile_onboarding_unpaired_hint,
    "One time" to R.string.mobile_one_time_6fea9e4d,
    "One time · date unavailable" to R.string.mobile_routine_date_unavailable,
    "Only continue if this is the computer whose QR code you just scanned. Confirming establishes an authenticated companion connection. Use a trusted Wi-Fi network or a tailnet; OpenMausBot does not encrypt local Wi-Fi traffic." to R.string.mobile_pairing_notice_scan,
    "Only continue if this is the computer whose QR code you just scanned. Confirming establishes an authenticated HTTPS companion connection." to R.string.mobile_pairing_notice_https,
    "Only while open" to R.string.mobile_settings_only_while_open,
    "Open" to R.string.mobile_open_cf9b7706,
    "Open %1\$s settings" to R.string.mobile_a11y_open_chat_settings,
    "Open chats, approve actions, and send new work from your phone." to R.string.mobile_onboarding_welcome_subtitle,
    "Open desktop" to R.string.mobile_open_desktop_cd6f8218,
    "Open links to other computer files from the original message." to R.string.mobile_file_open_other_computer,
    "Open live cloud desktop" to R.string.mobile_open_live_cloud_desktop_88662ef7,
    "Open live cloud desktop?" to R.string.mobile_open_live_cloud_desktop_f2746abf,
    "Open live screen & desktop controls" to R.string.mobile_slash_computer_description,
    "Open notification settings" to R.string.mobile_settings_open_notification_settings,
    "Open Settings" to R.string.mobile_open_settings_134635e9,
    "Open task" to R.string.mobile_open_task_a1f1752a,
    "Open thread" to R.string.mobile_open_thread,
    "Open the chat to review SKILL.md" to R.string.mobile_open_the_chat_to_review_skill_md_6225775b,
    "Open the OpenMausBot app once after updating. If this phone still isn't connected, pair it before sharing." to R.string.mobile_share_not_paired,
    "Open updates" to R.string.mobile_open_updates_2c80d633,
    "Opening %1\$s…" to R.string.mobile_chat_opening_file,
    "Opening…" to R.string.mobile_opening_b1b8530b,
    "OpenMausBot" to R.string.mobile_openmausbot_befe710d,
    "OpenMausBot couldn't read %1\$s. Try exporting it to Files first." to R.string.mobile_share_unreadable,
    "OpenMausBot couldn't send this. Please try again." to R.string.mobile_share_generic_error,
    "OpenMausBot is trying the saved connection automatically." to R.string.mobile_settings_troubleshooting_connecting,
    "OpenMausBot keeps a permanent notification while this is on, so scheduled reminders and routine results reach you even with the app fully closed." to R.string.mobile_settings_background_on_description,
    "OpenMausMobile" to R.string.app_name,
    "Or enter the address" to R.string.mobile_or_enter_the_address_f74dcf1c,
    "Organize bots" to R.string.mobile_organize_bots_08f4197e,
    "Organize bots into a section" to R.string.mobile_organize_bots_into_a_section_9293c5af,
    "Other" to R.string.mobile_other_6e6a6f20,
    "Other computers" to R.string.mobile_settings_other_computers,
    "Other ways to connect" to R.string.mobile_other_ways_to_connect_d9e8585d,
    "Pair again" to R.string.mobile_pair_again_379e2bf5,
    "Pair this phone with OpenMausBot to see your chats and respond to your bots." to R.string.mobile_onboarding_unpaired_body,
    "Pair with a computer" to R.string.mobile_pair_with_a_computer_51716e03,
    "Pair with this computer" to R.string.mobile_pair_with_this_computer_8420e8b3,
    "Pairing failed." to R.string.mobile_pairing_failed,
    "Past run receipts remain available." to R.string.mobile_past_run_receipts_remain_available_fd5e2bbd,
    "Pause" to R.string.mobile_pause_781961bc,
    "Paused" to R.string.mobile_paused_c7dfb6f1,
    "Pending" to R.string.mobile_pending_96f608c1,
    "Photo Library" to R.string.mobile_photo_library_26def20d,
    "Pick a voice for this agent before enabling speech." to R.string.mobile_profile_pick_voice,
    "Pick an agent voice or configure a workspace default on your computer first." to R.string.mobile_profile_preview_refused,
    "Pick up the same conversations from your computer." to R.string.mobile_onboarding_conversations,
    "Pin" to R.string.mobile_a11y_pin,
    "Pinned" to R.string.mobile_roster_pinned,
    "Pinned bots stay in Pinned until you unpin them." to R.string.mobile_section_pinned_stays,
    "plus" to R.string.mobile_plus_6a8437dd,
    "PNG, JPEG, GIF, or WebP, up to 10 MB. Images are stored on your paired computer and loaded with this phone's pairing token." to R.string.mobile_profile_avatar_footer,
    "Point the camera at the QR code on your computer" to R.string.mobile_point_the_camera_at_the_qr_code_on_77e56351,
    "Preparing attachments…" to R.string.mobile_preparing_attachments_343475f3,
    "Preparing your share…" to R.string.mobile_share_preparing,
    "Preview" to R.string.mobile_preview_f1fbb2b4,
    "Preview voice" to R.string.mobile_preview_voice_560a6fec,
    "Previous version" to R.string.mobile_previous_version_989537a3,
    "Primary account" to R.string.mobile_primary_account_32f2184e,
    "Private by design" to R.string.mobile_private_by_design_3aaa9fd1,
    "Prompt" to R.string.mobile_prompt_a817d7eb,
    "Provider" to R.string.mobile_provider_7ceee3f3,
    "Provider accounts and API keys stay on your computer. Default sends no reasoning level and lets the provider decide." to R.string.mobile_model_settings_footer,
    "Queued" to R.string.mobile_queued_6a599877,
    "queued" to R.string.mobile_queued_efcc7714,
    "Queued — waiting for an available slot" to R.string.mobile_updates_queued_waiting,
    "Quick replies" to R.string.mobile_quick_replies_c14223c4,
    "Ran %1\$s steps" to R.string.mobile_ran_steps,
    "Reading shared content" to R.string.mobile_reading_shared_content_61a0de26,
    "Reasoning effort" to R.string.mobile_reasoning_effort_cd32c0f5,
    "Recent changes" to R.string.mobile_recent_changes_1bfd2320,
    "Reduced" to R.string.mobile_activity_reduced,
    "Refresh" to R.string.mobile_refresh_56e3badc,
    "Refreshing…" to R.string.mobile_refreshing_96141178,
    "Remove" to R.string.mobile_remove_e963907d,
    "Remove this computer" to R.string.mobile_settings_remove_this_computer,
    "Removes the pairing from this phone only. To stop it reaching the computer at all, remove the device in OpenMausBot → Settings → Phone." to R.string.mobile_settings_unpair_footer,
    "Rename %1\$s" to R.string.mobile_rename_taskrules_title_task_054bec52,
    "Rename thread" to R.string.mobile_rename_thread,
    "Repeat interval, %1\$s minutes" to R.string.mobile_a11y_repeat_interval,
    "Requesting camera access…" to R.string.mobile_requesting_camera_access_30e104c0,
    "Reset" to R.string.mobile_reset_44c57abd,
    "Reset quick replies?" to R.string.mobile_reset_quick_replies_4d3d1256,
    "Respond when a bot needs you" to R.string.mobile_respond_when_a_bot_needs_you_96973325,
    "Resume" to R.string.mobile_resume_b3bd0b5a,
    "Retry" to R.string.mobile_retry_9f5cd8a2,
    "Retry send" to R.string.mobile_retry_send_6a2d9259,
    "Retry the last turn with fresh context" to R.string.mobile_slash_retry_description,
    "Review approvals without going back to your desk." to R.string.mobile_onboarding_approvals,
    "Review the complete SKILL.md" to R.string.mobile_review_the_complete_skill_md_61fb9a9a,
    "Rounded" to R.string.mobile_rounded_c5aa340f,
    "Routine failures" to R.string.notification_channel_routine,
    "Routine name" to R.string.mobile_routine_name_9a8a0dda,
    "Routine schedules are safe to manage here. Provider keys, webhook secrets, pairing, revocation, Local VM, and agent execution policy stay on your computer." to R.string.mobile_settings_workspace_footer,
    "Routine timeout" to R.string.mobile_a11y_routine_timeout,
    "Routines" to R.string.mobile_routines_a445e5ad,
    "Run" to R.string.mobile_run_b1b39260,
    "Run all automated tests" to R.string.mobile_run_all_automated_tests_4032d93f,
    "Run now" to R.string.mobile_run_now_2af00e23,
    "Run receipts" to R.string.mobile_run_receipts_9115568f,
    "Run tests" to R.string.mobile_run_tests_fcab481b,
    "Running" to R.string.mobile_running_73989d9c,
    "running" to R.string.mobile_running_3c49d9cc,
    "Running %1\$s steps" to R.string.mobile_running_steps,
    "Runs every" to R.string.mobile_runs_every_dd679464,
    "Sat" to R.string.mobile_routine_saturday_short,
    "Saturday" to R.string.mobile_routine_saturday,
    "Save" to R.string.mobile_save_efc007a3,
    "Save profile changes" to R.string.mobile_save_profile_changes_49c8333d,
    "Scan QR Code" to R.string.mobile_scan_qr_code_04e3f103,
    "Scan the QR code, check the computer name, and confirm. The address and one-time credential are filled securely for you." to R.string.mobile_pair_scanner_hint,
    "Scanner unavailable" to R.string.mobile_scanner_unavailable_cc42e33b,
    "Schedule" to R.string.mobile_schedule_0a8adac9,
    "Schedule recurring or one-time agent work." to R.string.mobile_schedule_recurring_or_one_time_agent_wor_3c7526bf,
    "Screenshot unavailable" to R.string.mobile_screenshot_unavailable_cfe6fcbe,
    "Search" to R.string.mobile_search_bce06414,
    "Search apps" to R.string.mobile_search_apps_ca3ce8f3,
    "Search threads" to R.string.mobile_search_threads_006299d3,
    "Searching this network needs %1\$s, which is still off. The QR code and the address below work without it." to R.string.mobile_discovery_permission_hint,
    "Section name" to R.string.mobile_section_name_75e2b3c1,
    "Secure HTTPS" to R.string.mobile_share_route_secure_https,
    "Select text" to R.string.mobile_select_text_9d49219e,
    "Selected days" to R.string.mobile_selected_days_7890ff6e,
    "Send" to R.string.mobile_send_9bc2575c,
    "SEND TO" to R.string.mobile_send_to_bd1c2c33,
    "Send to" to R.string.mobile_send_to_b98cc23a,
    "Send to OpenMausBot" to R.string.mobile_send_to_openmausbot_4dffcb75,
    "Send up to 4 items at a time." to R.string.mobile_share_too_many_items,
    "Sending securely…" to R.string.mobile_share_sending_securely,
    "Sending took too long. Check your connection and try again." to R.string.mobile_share_send_timed_out,
    "Sending…" to R.string.mobile_sending_cf765512,
    "Sends after this turn" to R.string.mobile_composer_sends_after_turn,
    "Sends into this turn" to R.string.mobile_composer_sends_into_turn,
    "Sent" to R.string.mobile_share_sent,
    "Settings" to R.string.mobile_settings_c7f73bb5,
    "sha256 %1\$s" to R.string.mobile_sha256_reviewed_take_8_d4013810,
    "Share" to R.string.mobile_share_09ca55ca,
    "Share %1\$s" to R.string.mobile_file_share_title,
    "Share as JSON" to R.string.mobile_share_as_json_df80c8e6,
    "Share transcript" to R.string.mobile_share_transcript_004e223a,
    "SHARING" to R.string.mobile_sharing_f789760c,
    "Show" to R.string.mobile_show_d97d1ee3,
    "Show diff" to R.string.mobile_show_diff_78016e77,
    "Show full address" to R.string.mobile_show_full_address_889be5c7,
    "Showing what was connected last time. Your computer could not open its credential store just now, so these accounts could not be re-checked. Nothing has been disconnected — restarting OpenMausBot on your computer usually clears this." to R.string.mobile_showing_what_was_connected_last_ti_62107fa4,
    "Shown while OpenMausBot stays connected in the background" to R.string.notification_channel_always_on_desc,
    "SLASH COMMANDS" to R.string.mobile_slash_commands_e7bb82f3,
    "Slash commands" to R.string.mobile_slash_commands_efce77da,
    "Snoozed" to R.string.mobile_thread_snoozed,
    "Something went wrong" to R.string.mobile_something_went_wrong_8d886c0b,
    "Source: %1\$s" to R.string.mobile_source_skill_source_unknown_6370895d,
    "Speak replies" to R.string.mobile_speak_replies_90b05ae0,
    "Square" to R.string.mobile_square_82810cb9,
    "Start a fresh conversation in %1\$s" to R.string.mobile_action_new_conversation_in_channel,
    "Start a fresh thread with %1\$s" to R.string.mobile_action_new_thread_for_bot,
    "Start dictation" to R.string.mobile_start_dictation_ee00527b,
    "Status" to R.string.mobile_settings_status_label,
    "Stay in the loop" to R.string.mobile_onboarding_notifications_title,
    "Steer" to R.string.mobile_steer_02f4a3c6,
    "Steer and redirect active execution" to R.string.mobile_slash_steer_description,
    "Steering…" to R.string.mobile_steering_eabc6c5d,
    "Steps fold into one line. Failures always show." to R.string.mobile_activity_reduced_caption,
    "Stop dictation" to R.string.mobile_stop_dictation_96ad53f1,
    "Stop if still running after" to R.string.mobile_stop_if_still_running_after_45efb175,
    "Stop snoozing" to R.string.mobile_stop_snoozing,
    "Stop the current turn" to R.string.mobile_action_stop_turn,
    "Stop this bot before changing its model." to R.string.mobile_model_busy_note,
    "Structured transcript data" to R.string.mobile_action_structured_transcript,
    "Submit answer" to R.string.mobile_submit_answer_bf80bc31,
    "Submit answers" to R.string.mobile_submit_answers_988c4130,
    "Sun" to R.string.mobile_routine_sunday_short,
    "Sunday" to R.string.mobile_routine_sunday,
    "Switch, rename or remove one" to R.string.mobile_action_manage_threads,
    "Take your bots with you" to R.string.mobile_onboarding_welcome_title,
    "Tap to preview" to R.string.mobile_tap_to_preview_fa5ce0ea,
    "Text" to R.string.mobile_share_text,
    "That computer did not answer with an address. Enter the address shown in Phone settings instead." to R.string.mobile_pairing_no_address,
    "That image is larger than 10 MB." to R.string.mobile_that_image_is_larger_than_10_mb_baaf657b,
    "That is not an OpenMausBot pairing QR code." to R.string.mobile_pairing_invalid_qr,
    "That link couldn't be opened on this phone." to R.string.mobile_file_open_link_failed,
    "That text is too large to share. Send a shorter selection." to R.string.mobile_share_too_much_text,
    "The authorization page could not be opened. Check your browser restrictions and try again." to R.string.mobile_connected_apps_auth_page_failed,
    "The Chatterbox server is not connected" to R.string.mobile_profile_chatterbox_unconfigured,
    "The chip row is hidden while this list is empty." to R.string.mobile_the_chip_row_is_hidden_while_this__209bd34b,
    "The generated audio could not be played." to R.string.mobile_the_generated_audio_could_not_be_played_fc933657,
    "The voice choice belongs to this agent. Workspace default uses the shared voice selected on your computer." to R.string.mobile_profile_voice_ready_footer,
    "There aren't any bots or channels to send this to yet. Create one on your computer first." to R.string.mobile_share_no_destinations,
    "There isn't any text, link, image, or supported document to send." to R.string.mobile_share_nothing_supported,
    "Thinking…" to R.string.mobile_thinking_a60d9c9c,
    "This app restarted before the pairing finished. That one-time code is never reused, because it may already have been redeemed. Start pairing again on your computer and scan the new QR code." to R.string.mobile_pairing_rescan_notice,
    "This bot's computer is only captured while it is working." to R.string.mobile_this_bot_s_computer_is_only_captured_whi_df844363,
    "This computer" to R.string.mobile_this_computer_4ccce6f4,
    "This computer is connected and responding normally." to R.string.mobile_settings_troubleshooting_live,
    "This conversation will be deleted. Generated files are kept." to R.string.mobile_this_conversation_will_be_deleted__af9201c8,
    "This creates a new version and continues from there." to R.string.mobile_this_creates_a_new_version_and_con_9a5d779d,
    "This image couldn't be displayed." to R.string.mobile_this_image_couldn_t_be_displayed_34d0827e,
    "This link can't be opened on this phone." to R.string.mobile_chat_open_link_failed,
    "This link can't be opened securely." to R.string.mobile_chat_open_link_insecure,
    "This phone has no browser available to open the authorization page." to R.string.mobile_connected_apps_no_browser,
    "This phone is not paired with a computer." to R.string.mobile_settings_troubleshooting_not_paired,
    "This phone was removed from the computer. Pair it again to reconnect." to R.string.mobile_settings_troubleshooting_unpaired,
    "This phone was unpaired" to R.string.mobile_this_phone_was_unpaired_09273604,
    "This phone was unpaired on the computer." to R.string.mobile_phone_unpaired_banner,
    "This phone's pairing has expired. Open OpenMausBot and pair it again." to R.string.mobile_share_pairing_expired,
    "This proposal was created by an older build and cannot be safely enabled. Deny it and ask the bot to create it again." to R.string.mobile_old_proposal_hint,
    "This removes the saved connection from this phone only." to R.string.mobile_this_removes_the_saved_connection__54db6818,
    "This removes the saved connection from this phone only. Another saved computer will stay available." to R.string.mobile_this_removes_the_saved_connection__45c7d71e,
    "This restores the four chips the app came with and discards your own." to R.string.mobile_this_restores_the_four_chips_the_a_ca291a72,
    "This saved connection is no longer available on this phone. Remove it and pair again." to R.string.mobile_share_saved_connection_unavailable,
    "This thread as Markdown" to R.string.mobile_action_markdown_transcript,
    "Thought Process" to R.string.mobile_thought_process_1756ad28,
    "Threads" to R.string.mobile_threads_bb12e8aa,
    "Threads & Routines" to R.string.mobile_threads_routines_65d7efcd,
    "Thu" to R.string.mobile_routine_thursday_short,
    "Thursday" to R.string.mobile_routine_thursday,
    "Time" to R.string.mobile_time_6c82e6dd,
    "Time-sensitive prompts that need an answer" to R.string.notification_channel_blocking_desc,
    "Title" to R.string.mobile_title_768e0c1c,
    "To generate images, configure the shared image provider in OpenMausBot on your computer. Provider keys cannot be added from a phone." to R.string.mobile_profile_generate_blocked,
    "To review" to R.string.mobile_to_review_066f77ce,
    "Today %1\$s" to R.string.mobile_date_today_with_time,
    "Touch and hold the text to select part of it." to R.string.mobile_touch_and_hold_the_text_to_select__efc64a9c,
    "Troubleshooting" to R.string.mobile_settings_troubleshooting,
    "Try again" to R.string.mobile_try_again_042c862e,
    "Try reconnecting" to R.string.mobile_settings_try_reconnecting,
    "Tue" to R.string.mobile_routine_tuesday_short,
    "Tuesday" to R.string.mobile_routine_tuesday,
    "Turn off" to R.string.mobile_settings_turn_off,
    "Turn on" to R.string.mobile_settings_turn_on,
    "Turned off in system settings" to R.string.mobile_settings_notifications_disabled,
    "Type your own answer" to R.string.mobile_type_your_own_answer_84cf9943,
    "Unarchive" to R.string.mobile_a11y_unarchive,
    "Unavailable" to R.string.mobile_model_unavailable,
    "Unknown" to R.string.mobile_unknown_bc7819b3,
    "Unlock this phone, then try sharing again." to R.string.mobile_unlock_phone,
    "Unpair" to R.string.mobile_unpair_9c293ad4,
    "Unpair this phone" to R.string.mobile_settings_unpair_this_phone,
    "Unpair this phone?" to R.string.mobile_settings_unpair_confirm_title,
    "Unpaired on the computer" to R.string.mobile_settings_unpaired_on_computer_status,
    "Unpin" to R.string.mobile_a11y_unpin,
    "Unread" to R.string.mobile_unread_07b032b5,
    "Until 6 PM" to R.string.mobile_until_6_pm,
    "Until 9 AM tomorrow" to R.string.mobile_until_9_am_tomorrow,
    "Until new activity" to R.string.mobile_until_new_activity,
    "Update OpenMausBot on this computer before sharing images." to R.string.mobile_share_image_support_unavailable,
    "Updates" to R.string.mobile_updates_c76d1807,
    "Upload image" to R.string.mobile_upload_image_f35dec5f,
    "Use %1\$s" to R.string.mobile_settings_use_computer,
    "Use another computer" to R.string.mobile_use_another_computer_ff6a1b80,
    "Use mascot" to R.string.mobile_use_mascot_0de90a12,
    "Use Open to view this file in a compatible app." to R.string.mobile_use_open_to_view_this_file_in_a_co_9a046473,
    "Use whatever Phone settings on your computer shows — a secure https:// address, an address on this network, or a Tailscale name like macbook.tail1234.ts.net:8810." to R.string.mobile_pair_manual_address_hint,
    "Uses this agent's selected model and computer setting on the paired computer." to R.string.mobile_uses_this_agent_s_selected_model_and_com_a3de7cdb,
    "View and manage threads" to R.string.mobile_slash_threads_description,
    "View Diff" to R.string.mobile_view_diff_39f85d34,
    "Voice" to R.string.mobile_voice_3091c844,
    "Voice engine" to R.string.mobile_voice_engine_3b4d8dea,
    "Waiting for a frame…" to R.string.mobile_waiting_for_a_frame_a772baa4,
    "Waiting on teammate" to R.string.mobile_waiting_on_teammate_158d309b,
    "Waiting on you" to R.string.mobile_waiting_on_you_edab5b72,
    "Watch %1\$s's computer" to R.string.mobile_watch_chat_name_s_computer_92efc119,
    "Watch computer" to R.string.mobile_watch_computer_c96208ca,
    "Webhooks" to R.string.mobile_webhooks_fdfe2da7,
    "Wed" to R.string.mobile_routine_wednesday_short,
    "Wednesday" to R.string.mobile_routine_wednesday,
    "Weekdays" to R.string.mobile_weekdays_4ffc67b6,
    "What %1\$s does" to R.string.mobile_overview_title,
    "What should the agent do?" to R.string.mobile_what_should_the_agent_do_b9526063,
    "What this agent does" to R.string.mobile_what_this_agent_does_82aa1b56,
    "What this bot does" to R.string.mobile_what_this_bot_does_7a664f47,
    "What's next?" to R.string.mobile_what_s_next_3d4b36bc,
    "When a bot replies or finishes a turn — pops up with sound, like a normal message" to R.string.notification_channel_done_desc,
    "When a bot stops for an answer, is mid-task, or finishes something, it shows up here." to R.string.mobile_when_a_bot_stops_for_an_answer_is_mid_ta_6141a0c8,
    "When a scheduled routine fails" to R.string.notification_channel_routine_desc,
    "Where does it run?" to R.string.mobile_where_does_it_run_6e4a5297,
    "Who" to R.string.mobile_who_7d531617,
    "Won't" to R.string.mobile_won_t_f51153fe,
    "Work" to R.string.mobile_work_00040bab,
    "Work, Personal, Client…" to R.string.mobile_work_personal_client_7d6a18a4,
    "Working" to R.string.mobile_thread_working,
    "Workspace" to R.string.mobile_settings_workspace_section,
    "Workspace default" to R.string.mobile_workspace_default_b81e277f,
    "Yesterday" to R.string.mobile_yesterday_da24830f,
    "Yesterday %1\$s" to R.string.mobile_date_yesterday_with_time,
    "You choose which trusted computer this phone connects to." to R.string.mobile_onboarding_trusted_computer,
    "You'll need a new pairing code to connect again." to R.string.mobile_settings_unpair_confirm_message,
    "Your chats, in your pocket" to R.string.mobile_your_chats_in_your_pocket_91291d76,
    "Your computer could not open its credential store, so it cannot say which accounts are connected. Nothing has been disconnected — restarting OpenMausBot on your computer usually clears this." to R.string.mobile_your_computer_could_not_open_its_c_fa640d75,
    "Your computer's built-in voices are unavailable" to R.string.mobile_profile_builtin_voices_unavailable,
    "Your computer's built-in voices need no key, and it reports none it can use. Switch the voice engine in OpenMausBot on the computer to turn speech back on." to R.string.mobile_profile_system_voice_unconfigured_footer
)

@Composable
internal fun localizedMobileCopy(source: String): String {
    localizedCopyResources[source]?.let { return stringResource(it) }
    Regex("""^Ask (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_composer_ask_bot, it.groupValues[1]) }
    Regex("""^Today (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_date_today_with_time, it.groupValues[1]) }
    Regex("""^Yesterday (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_date_yesterday_with_time, it.groupValues[1]) }
    Regex("""^(.+) isn't a supported attachment\. Try an image, PDF, text, Word, Excel, or PowerPoint file\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_chat_attachment_unsupported, it.groupValues[1]) }
    Regex("""^(.+) is larger than the (.+) remaining attachment limit\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_attachment_too_large, it.groupValues[1], it.groupValues[2]) }
    Regex("""^OpenMausBot couldn't read (.+)\. Try exporting it to Files first\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_unreadable, it.groupValues[1]) }
    Regex("""^Couldn't reach (.+)\. Keep OpenMausBot open and Phone access on, then try again\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_offline, it.groupValues[1]) }
    Regex("""^(.+) isn't a supported document\. Try PDF, text, Word, Excel, or PowerPoint\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_unsupported_document, it.groupValues[1]) }
    Regex("""^(.+) is larger than (\d+) MB\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_too_large, it.groupValues[1], it.groupValues[2].toInt()) }
    Regex("""^No app on this phone can open (.+)\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_file_no_viewer, it.groupValues[1]) }
    Regex("""^Share (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_file_share_title, it.groupValues[1]) }
    Regex("""^No app on this phone can share (.+)\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_file_no_share_app, it.groupValues[1]) }
    Regex("""^(.+)'s current model doesn't support images\. Choose another bot or share without the image\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_bot_image_compatibility, it.groupValues[1]) }
    Regex("""^Bot · (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_bot_thread, it.groupValues[1]) }
    Regex("""^Channel · (.+)$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_channel_thread, it.groupValues[1]) }
    Regex("""^(\d+) links$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_links, it.groupValues[1].toInt()) }
    Regex("""^(\d+) text items$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_text_items, it.groupValues[1].toInt()) }
    Regex("""^(\d+) unsupported items were left out\.$""")
        .matchEntire(source)?.let { return stringResource(R.string.mobile_share_items_omitted, it.groupValues[1].toInt()) }
    return source
}
