// Generated by ios/parity/achievements-catalog.mjs from
// shared/achievements-catalog.ts and src/locales: do not edit by hand.
// The catalog has English and French; Portuguese falls back to English
// except for the reward names, which the renderer's locales carry.
import Foundation

public extension AchievementDefinition {
    static let catalog: [AchievementDefinition] = [
        AchievementDefinition(
            id: "first-words", category: .onboarding, icon: "MessageCircle", points: 5, hidden: false,
            name: AchievementText(en: "First Words", fr: "Premiers mots", ptBR: "First Words"),
            description: AchievementText(en: "Send your first message to a bot.", fr: "Envoyez votre premier message à un robot.", ptBR: "Send your first message to a bot."),
            hint: nil,
            rewards: [.title(id: "rookie", name: AchievementText(en: "Rookie", fr: "Recrue", ptBR: "Rookie"))]
        ),
        AchievementDefinition(
            id: "hello-bot", category: .onboarding, icon: "Bot", points: 10, hidden: false,
            name: AchievementText(en: "It's Alive!", fr: "Il est vivant!", ptBR: "It's Alive!"),
            description: AchievementText(en: "Create your first bot.", fr: "Créez votre premier robot.", ptBR: "Create your first bot."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "outline", name: AchievementText(en: "Outline", fr: "Contour", ptBR: "Outline"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "makeover", category: .onboarding, icon: "Palette", points: 10, hidden: false,
            name: AchievementText(en: "Makeover", fr: "Relooking", ptBR: "Makeover"),
            description: AchievementText(en: "Change a bot's look: its character, color or skin.", fr: "Changez l'allure d'un robot : son personnage, sa couleur ou son skin.", ptBR: "Change a bot's look: its character, color or skin."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "gold", name: AchievementText(en: "Gold", fr: "Or", ptBR: "Gold"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "right-hand", category: .onboarding, icon: "Crown", points: 20, hidden: false,
            name: AchievementText(en: "Right Hand", fr: "Bras droit", ptBR: "Right Hand"),
            description: AchievementText(en: "Choose a Primary Bot.", fr: "Choisissez un Robot principal.", ptBR: "Choose a Primary Bot."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "frost", name: AchievementText(en: "Ice", fr: "Glace", ptBR: "Ice"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "dressing-room", category: .onboarding, icon: "Shirt", points: 20, hidden: false,
            name: AchievementText(en: "Dressing Room", fr: "Salle d'essayage", ptBR: "Dressing Room"),
            description: AchievementText(en: "Dress bots as three different characters.", fr: "Habillez des robots en trois personnages différents.", ptBR: "Dress bots as three different characters."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "gold", name: AchievementText(en: "Gold", fr: "Or", ptBR: "Gold"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "small-family", category: .onboarding, icon: "Users", points: 20, hidden: false,
            name: AchievementText(en: "Small Family", fr: "Petite famille", ptBR: "Small Family"),
            description: AchievementText(en: "Create three bots.", fr: "Créez trois robots.", ptBR: "Create three bots."),
            hint: nil,
            rewards: [.character(id: "bunbu", name: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "on-schedule", category: .productivity, icon: "CalendarClock", points: 10, hidden: false,
            name: AchievementText(en: "On Schedule", fr: "Réglé comme une horloge", ptBR: "On Schedule"),
            description: AchievementText(en: "Create your first routine.", fr: "Créez votre première routine.", ptBR: "Create your first routine."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "velvet", name: AchievementText(en: "Velvet", fr: "Velours", ptBR: "Velvet"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "routine-five", category: .productivity, icon: "Repeat", points: 20, hidden: false,
            name: AchievementText(en: "Automation Fan", fr: "Fan d'automatisation", ptBR: "Automation Fan"),
            description: AchievementText(en: "Create five routines.", fr: "Créez cinq routines.", ptBR: "Create five routines."),
            hint: nil,
            rewards: [.title(id: "automator", name: AchievementText(en: "Automator", fr: "Automatiseur", ptBR: "Automator"))]
        ),
        AchievementDefinition(
            id: "clockwork", category: .productivity, icon: "Timer", points: 50, hidden: false,
            name: AchievementText(en: "Clockwork", fr: "Mécanique de précision", ptBR: "Clockwork"),
            description: AchievementText(en: "Have your routines run on seven different days.", fr: "Faites rouler vos routines sept jours différents.", ptBR: "Have your routines run on seven different days."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "chrome", name: AchievementText(en: "Chrome", fr: "Chrome", ptBR: "Chrome"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "well-oiled", category: .productivity, icon: "Cog", points: 100, hidden: false,
            name: AchievementText(en: "Well-Oiled Machine", fr: "Machine bien huilée", ptBR: "Well-Oiled Machine"),
            description: AchievementText(en: "Have your routines complete fifty runs.", fr: "Faites compléter cinquante exécutions à vos routines.", ptBR: "Have your routines complete fifty runs."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "molten", name: AchievementText(en: "Molten", fr: "Magma", ptBR: "Molten"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "gatekeeper", category: .productivity, icon: "ShieldCheck", points: 5, hidden: false,
            name: AchievementText(en: "Gatekeeper", fr: "Gardien", ptBR: "Gatekeeper"),
            description: AchievementText(en: "Answer a bot's approval request.", fr: "Répondez à une demande d'approbation d'un robot.", ptBR: "Answer a bot's approval request."),
            hint: nil,
            rewards: [.title(id: "gatekeeper", name: AchievementText(en: "Gatekeeper", fr: "Gardien", ptBR: "Gatekeeper"))]
        ),
        AchievementDefinition(
            id: "trusted-judge", category: .productivity, icon: "Scale", points: 20, hidden: false,
            name: AchievementText(en: "Trusted Judge", fr: "Juge de confiance", ptBR: "Trusted Judge"),
            description: AchievementText(en: "Answer twenty-five approval requests.", fr: "Répondez à vingt-cinq demandes d'approbation.", ptBR: "Answer twenty-five approval requests."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "neon", name: AchievementText(en: "Neon", fr: "Néon", ptBR: "Neon"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "slash-and-learn", category: .productivity, icon: "Slash", points: 5, hidden: false,
            name: AchievementText(en: "Slash and Learn", fr: "Barre oblique", ptBR: "Slash and Learn"),
            description: AchievementText(en: "Run a slash command from the composer.", fr: "Lancez une commande « / » depuis la zone de saisie.", ptBR: "Run a slash command from the composer."),
            hint: nil,
            rewards: [.title(id: "commander", name: AchievementText(en: "Commander", fr: "Commandant", ptBR: "Commander"))]
        ),
        AchievementDefinition(
            id: "command-collector", category: .productivity, icon: "SquareTerminal", points: 20, hidden: false,
            name: AchievementText(en: "Command Collector", fr: "Collectionneur de commandes", ptBR: "Command Collector"),
            description: AchievementText(en: "Use five different slash commands.", fr: "Utilisez cinq commandes « / » différentes.", ptBR: "Use five different slash commands."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "circuit", name: AchievementText(en: "Circuit", fr: "Circuit", ptBR: "Circuit"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "paperclip", category: .productivity, icon: "Paperclip", points: 10, hidden: false,
            name: AchievementText(en: "See Attached", fr: "Voir pièce jointe", ptBR: "See Attached"),
            description: AchievementText(en: "Attach a file or an image to a message.", fr: "Joignez un fichier ou une image à un message.", ptBR: "Attach a file or an image to a message."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "gold", name: AchievementText(en: "Gold", fr: "Or", ptBR: "Gold"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "zip-it", category: .productivity, icon: "FileArchive", points: 10, hidden: false,
            name: AchievementText(en: "Zip It", fr: "Tout compressé", ptBR: "Zip It"),
            description: AchievementText(en: "Hand a bot a .zip archive.", fr: "Donnez une archive .zip à un robot.", ptBR: "Hand a bot a .zip archive."),
            hint: nil,
            rewards: [.skin(character: "trombi", skin: "gold", name: AchievementText(en: "Gold", fr: "Or", ptBR: "Gold"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "librarian", category: .productivity, icon: "FolderOpen", points: 5, hidden: false,
            name: AchievementText(en: "Librarian", fr: "Bibliothécaire", ptBR: "Librarian"),
            description: AchievementText(en: "Open a bot's Library to see its files.", fr: "Ouvrez la Bibliothèque d'un robot pour voir ses fichiers.", ptBR: "Open a bot's Library to see its files."),
            hint: nil,
            rewards: [.title(id: "librarian", name: AchievementText(en: "Librarian", fr: "Bibliothécaire", ptBR: "Librarian"))]
        ),
        AchievementDefinition(
            id: "chatterbox", category: .productivity, icon: "MessagesSquare", points: 20, hidden: false,
            name: AchievementText(en: "Chatterbox", fr: "Moulin à paroles", ptBR: "Chatterbox"),
            description: AchievementText(en: "Send one hundred messages.", fr: "Envoyez cent messages.", ptBR: "Send one hundred messages."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "neon", name: AchievementText(en: "Neon", fr: "Néon", ptBR: "Neon"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "wordsmith", category: .productivity, icon: "Feather", points: 50, hidden: false,
            name: AchievementText(en: "Wordsmith", fr: "Plume d'or", ptBR: "Wordsmith"),
            description: AchievementText(en: "Send one thousand messages.", fr: "Envoyez mille messages.", ptBR: "Send one thousand messages."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "inferno", name: AchievementText(en: "Inferno", fr: "Brasier", ptBR: "Inferno"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "multitasker", category: .power, icon: "Split", points: 20, hidden: false,
            name: AchievementText(en: "Multitasker", fr: "Multitâche", ptBR: "Multitasker"),
            description: AchievementText(en: "Send a request as a parallel task while the bot is busy.", fr: "Envoyez une demande en tâche parallèle pendant que le robot travaille.", ptBR: "Send a request as a parallel task while the bot is busy."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "chrome", name: AchievementText(en: "Chrome", fr: "Chrome", ptBR: "Chrome"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "juggler", category: .power, icon: "Layers", points: 50, hidden: false,
            name: AchievementText(en: "Juggler", fr: "Jongleur", ptBR: "Juggler"),
            description: AchievementText(en: "Start ten parallel tasks.", fr: "Lancez dix tâches parallèles.", ptBR: "Start ten parallel tasks."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "holo", name: AchievementText(en: "Holographic", fr: "Holographique", ptBR: "Holographic"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "delegator", category: .power, icon: "Network", points: 20, hidden: false,
            name: AchievementText(en: "Delegator", fr: "Délégateur", ptBR: "Delegator"),
            description: AchievementText(en: "Have a bot of yours hand work to a sub-agent.", fr: "Faites confier du travail à un sous-agent par un de vos robots.", ptBR: "Have a bot of yours hand work to a sub-agent."),
            hint: nil,
            rewards: [.skin(character: "trombi", skin: "neon", name: AchievementText(en: "Neon", fr: "Néon", ptBR: "Neon"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "hands-on", category: .power, icon: "MousePointerClick", points: 20, hidden: false,
            name: AchievementText(en: "Hands On", fr: "Aux commandes", ptBR: "Hands On"),
            description: AchievementText(en: "Take control of a bot's computer.", fr: "Prenez le contrôle de l'ordinateur d'un robot.", ptBR: "Take control of a bot's computer."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "chrome", name: AchievementText(en: "Chrome", fr: "Chrome", ptBR: "Chrome"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "autopilot", category: .power, icon: "Navigation", points: 20, hidden: false,
            name: AchievementText(en: "Autopilot", fr: "Pilote automatique", ptBR: "Autopilot"),
            description: AchievementText(en: "Let a bot pick the right computer by itself (Works on: Auto).", fr: "Laissez un robot choisir le bon ordinateur lui-même (Travaille sur : Auto).", ptBR: "Let a bot pick the right computer by itself (Works on: Auto)."),
            hint: nil,
            rewards: [.skin(character: "trombi", skin: "chrome", name: AchievementText(en: "Chrome", fr: "Chrome", ptBR: "Chrome"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "great-power", category: .power, icon: "Zap", points: 50, hidden: false,
            name: AchievementText(en: "With Great Power", fr: "Grands pouvoirs", ptBR: "With Great Power"),
            description: AchievementText(en: "Grant a bot Full access, then bring it back to Ask.", fr: "Accordez l'Accès complet à un robot, puis ramenez-le à Demander.", ptBR: "Grant a bot Full access, then bring it back to Ask."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "holo", name: AchievementText(en: "Holographic", fr: "Holographique", ptBR: "Holographic"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "palette", category: .power, icon: "Search", points: 5, hidden: false,
            name: AchievementText(en: "Quick Finder", fr: "Trouve-tout", ptBR: "Quick Finder"),
            description: AchievementText(en: "Open the command palette.", fr: "Ouvrez la palette de commandes.", ptBR: "Open the command palette."),
            hint: nil,
            rewards: [.appIcon(id: "glyph:cube")]
        ),
        AchievementDefinition(
            id: "keyboard-ninja", category: .power, icon: "Keyboard", points: 5, hidden: false,
            name: AchievementText(en: "Keyboard Ninja", fr: "Ninja du clavier", ptBR: "Keyboard Ninja"),
            description: AchievementText(en: "Open the keyboard shortcuts.", fr: "Ouvrez les raccourcis clavier.", ptBR: "Open the keyboard shortcuts."),
            hint: nil,
            rewards: [.appIcon(id: "glyph:spark")]
        ),
        AchievementDefinition(
            id: "first-call", category: .voice, icon: "Phone", points: 20, hidden: false,
            name: AchievementText(en: "On the Line", fr: "En ligne", ptBR: "On the Line"),
            description: AchievementText(en: "Call a bot with voice mode.", fr: "Appelez un robot en mode voix.", ptBR: "Call a bot with voice mode."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "neon", name: AchievementText(en: "Neon", fr: "Néon", ptBR: "Neon"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "long-call", category: .voice, icon: "PhoneCall", points: 20, hidden: false,
            name: AchievementText(en: "Long Distance", fr: "Interurbain", ptBR: "Long Distance"),
            description: AchievementText(en: "Stay on a voice call for ten minutes.", fr: "Restez dix minutes en appel vocal.", ptBR: "Stay on a voice call for ten minutes."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "crystal", name: AchievementText(en: "Crystal", fr: "Cristal", ptBR: "Crystal"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "polite-interrupt", category: .voice, icon: "Hand", points: 10, hidden: false,
            name: AchievementText(en: "Excuse Me", fr: "Pardon de vous interrompre", ptBR: "Excuse Me"),
            description: AchievementText(en: "Interrupt a bot mid-sentence on a call.", fr: "Interrompez un robot au milieu d'une phrase pendant un appel.", ptBR: "Interrupt a bot mid-sentence on a call."),
            hint: nil,
            rewards: [.title(id: "polite", name: AchievementText(en: "Polite", fr: "Poli", ptBR: "Polite"))]
        ),
        AchievementDefinition(
            id: "hotline", category: .voice, icon: "PhoneForwarded", points: 50, hidden: false,
            name: AchievementText(en: "Hotline", fr: "Ligne directe", ptBR: "Hotline"),
            description: AchievementText(en: "Make ten voice calls.", fr: "Faites dix appels vocaux.", ptBR: "Make ten voice calls."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "holo", name: AchievementText(en: "Holographic", fr: "Holographique", ptBR: "Holographic"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "sharing-is-caring", category: .collaboration, icon: "Share2", points: 20, hidden: false,
            name: AchievementText(en: "Sharing Is Caring", fr: "Partager, c'est donner", ptBR: "Sharing Is Caring"),
            description: AchievementText(en: "Share a bot with someone.", fr: "Partagez un robot avec quelqu'un.", ptBR: "Share a bot with someone."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "crystal", name: AchievementText(en: "Crystal", fr: "Cristal", ptBR: "Crystal"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "dream-team", category: .collaboration, icon: "UsersRound", points: 50, hidden: false,
            name: AchievementText(en: "Dream Team", fr: "Équipe de rêve", ptBR: "Dream Team"),
            description: AchievementText(en: "Talk in a group with another person and two bots.", fr: "Discutez dans un groupe avec une autre personne et deux robots.", ptBR: "Talk in a group with another person and two bots."),
            hint: nil,
            rewards: [.skin(character: "shape", skin: "galaxy", name: AchievementText(en: "Galaxy", fr: "Galaxie", ptBR: "Galaxy"), characterName: AchievementText(en: "Shapes", fr: "Formes", ptBR: "Shapes"))]
        ),
        AchievementDefinition(
            id: "direct-line", category: .collaboration, icon: "Send", points: 10, hidden: false,
            name: AchievementText(en: "Direct Line", fr: "Message direct", ptBR: "Direct Line"),
            description: AchievementText(en: "Send a direct message to a colleague.", fr: "Envoyez un message direct à un collègue.", ptBR: "Send a direct message to a colleague."),
            hint: nil,
            rewards: [.title(id: "connector", name: AchievementText(en: "Connector", fr: "Rassembleur", ptBR: "Connector"))]
        ),
        AchievementDefinition(
            id: "group-chat", category: .collaboration, icon: "MessageSquareMore", points: 10, hidden: false,
            name: AchievementText(en: "Round Table", fr: "Table ronde", ptBR: "Round Table"),
            description: AchievementText(en: "Send ten messages in groups.", fr: "Envoyez dix messages dans des groupes.", ptBR: "Send ten messages in groups."),
            hint: nil,
            rewards: [.title(id: "host", name: AchievementText(en: "Host", fr: "Animateur", ptBR: "Host"))]
        ),
        AchievementDefinition(
            id: "three-day", category: .streaks, icon: "Flame", points: 10, hidden: false,
            name: AchievementText(en: "Warming Up", fr: "On se réchauffe", ptBR: "Warming Up"),
            description: AchievementText(en: "Use Sagax three days in a row.", fr: "Utilisez Sagax trois jours de suite.", ptBR: "Use Sagax three days in a row."),
            hint: nil,
            rewards: [.title(id: "regular", name: AchievementText(en: "Regular", fr: "Habitué", ptBR: "Regular"))]
        ),
        AchievementDefinition(
            id: "week-streak", category: .streaks, icon: "CalendarCheck", points: 20, hidden: false,
            name: AchievementText(en: "Week Warrior", fr: "Guerrier de la semaine", ptBR: "Week Warrior"),
            description: AchievementText(en: "Use Sagax seven days in a row.", fr: "Utilisez Sagax sept jours de suite.", ptBR: "Use Sagax seven days in a row."),
            hint: nil,
            rewards: [.skin(character: "trombi", skin: "glitch", name: AchievementText(en: "Glitch", fr: "Glitch", ptBR: "Glitch"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "month-streak", category: .streaks, icon: "Rocket", points: 100, hidden: false,
            name: AchievementText(en: "Unstoppable", fr: "Inarrêtable", ptBR: "Unstoppable"),
            description: AchievementText(en: "Use Sagax thirty days in a row.", fr: "Utilisez Sagax trente jours de suite.", ptBR: "Use Sagax thirty days in a row."),
            hint: nil,
            rewards: [.skin(character: "owl", skin: "galaxy", name: AchievementText(en: "Galaxy", fr: "Galaxie", ptBR: "Galaxy"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "regular", category: .streaks, icon: "CalendarDays", points: 50, hidden: false,
            name: AchievementText(en: "Part of the Team", fr: "Membre de l'équipe", ptBR: "Part of the Team"),
            description: AchievementText(en: "Use Sagax on twenty different days.", fr: "Utilisez Sagax vingt jours différents.", ptBR: "Use Sagax on twenty different days."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "molten", name: AchievementText(en: "Molten", fr: "Magma", ptBR: "Molten"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu"))]
        ),
        AchievementDefinition(
            id: "bronze", category: .mastery, icon: "Medal", points: 10, hidden: false,
            name: AchievementText(en: "Bronze", fr: "Bronze", ptBR: "Bronze"),
            description: AchievementText(en: "Earn 100 points.", fr: "Obtenez 100 points.", ptBR: "Earn 100 points."),
            hint: nil,
            rewards: [.title(id: "bronze", name: AchievementText(en: "Bronze Operator", fr: "Opérateur bronze", ptBR: "Bronze Operator"))]
        ),
        AchievementDefinition(
            id: "silver", category: .mastery, icon: "Award", points: 20, hidden: false,
            name: AchievementText(en: "Silver", fr: "Argent", ptBR: "Silver"),
            description: AchievementText(en: "Earn 300 points.", fr: "Obtenez 300 points.", ptBR: "Earn 300 points."),
            hint: nil,
            rewards: [.title(id: "silver", name: AchievementText(en: "Silver Operator", fr: "Opérateur argent", ptBR: "Silver Operator"))]
        ),
        AchievementDefinition(
            id: "gold-tier", category: .mastery, icon: "Trophy", points: 50, hidden: false,
            name: AchievementText(en: "Gold", fr: "Or", ptBR: "Gold"),
            description: AchievementText(en: "Earn 600 points.", fr: "Obtenez 600 points.", ptBR: "Earn 600 points."),
            hint: nil,
            rewards: [.skin(character: "trombi", skin: "holo", name: AchievementText(en: "Holographic", fr: "Holographique", ptBR: "Holographic"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "platinum", category: .mastery, icon: "Gem", points: 100, hidden: false,
            name: AchievementText(en: "Platinum", fr: "Platine", ptBR: "Platinum"),
            description: AchievementText(en: "Unlock every achievement that is not a secret.", fr: "Débloquez tous les succès qui ne sont pas secrets.", ptBR: "Unlock every achievement that is not a secret."),
            hint: nil,
            rewards: [.skin(character: "bunbu", skin: "galaxy", name: AchievementText(en: "Galaxy", fr: "Galaxie", ptBR: "Galaxy"), characterName: AchievementText(en: "Bunbu", fr: "Bunbu", ptBR: "Bunbu")), .title(id: "platinum", name: AchievementText(en: "Platinum Sage", fr: "Sage platine", ptBR: "Platinum Sage"))]
        ),
        AchievementDefinition(
            id: "trombi-summoned", category: .secrets, icon: "Paperclip", points: 20, hidden: true,
            name: AchievementText(en: "It Looks Like You're Writing", fr: "On dirait que vous écrivez", ptBR: "It Looks Like You're Writing"),
            description: AchievementText(en: "Summon Trombi with its command. Trombi is yours for good.", fr: "Invoquez Trombi avec sa commande. Trombi est à vous pour de bon.", ptBR: "Summon Trombi with its command. Trombi is yours for good."),
            hint: AchievementText(en: "A retro command, typed alone in the composer, brings back an old office friend.", fr: "Une commande rétro, tapée seule dans la zone de saisie, ramène un vieil ami de bureau.", ptBR: "A retro command, typed alone in the composer, brings back an old office friend."),
            rewards: [.character(id: "trombi", name: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "konami", category: .secrets, icon: "Gamepad2", points: 50, hidden: true,
            name: AchievementText(en: "Up Up Down Down", fr: "Haut haut bas bas", ptBR: "Up Up Down Down"),
            description: AchievementText(en: "Enter the old cheat code.", fr: "Entrez le vieux code de triche.", ptBR: "Enter the old cheat code."),
            hint: AchievementText(en: "Gamers of a certain age know a code made of arrows.", fr: "Les joueurs d'une certaine époque connaissent un code fait de flèches.", ptBR: "Gamers of a certain age know a code made of arrows."),
            rewards: [.skin(character: "owl", skin: "lightning", name: AchievementText(en: "Lightning", fr: "Foudre", ptBR: "Lightning"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "night-owl", category: .secrets, icon: "Moon", points: 50, hidden: true,
            name: AchievementText(en: "Night Owl", fr: "Oiseau de nuit", ptBR: "Night Owl"),
            description: AchievementText(en: "Talk to your desktop mascot between midnight and 1 a.m.", fr: "Parlez à votre mascotte de bureau entre minuit et 1 h.", ptBR: "Talk to your desktop mascot between midnight and 1 a.m."),
            hint: AchievementText(en: "Owls are at their best after midnight.", fr: "Les hiboux sont à leur meilleur après minuit.", ptBR: "Owls are at their best after midnight."),
            rewards: [.skin(character: "owl", skin: "spirit", name: AchievementText(en: "Spirit", fr: "Esprit", ptBR: "Spirit"), characterName: AchievementText(en: "Owl", fr: "Hibou", ptBR: "Owl"))]
        ),
        AchievementDefinition(
            id: "good-bot", category: .secrets, icon: "Heart", points: 10, hidden: true,
            name: AchievementText(en: "Who's a Good Bot?", fr: "Qui est un bon robot?", ptBR: "Who's a Good Bot?"),
            description: AchievementText(en: "Pet your mascot fifty times.", fr: "Flattez votre mascotte cinquante fois.", ptBR: "Pet your mascot fifty times."),
            hint: AchievementText(en: "Your mascot loves a little affection.", fr: "Votre mascotte adore un peu d'affection.", ptBR: "Your mascot loves a little affection."),
            rewards: [.title(id: "petter", name: AchievementText(en: "Bot Whisperer", fr: "Charmeur de robots", ptBR: "Bot Whisperer"))]
        ),
        AchievementDefinition(
            id: "best-friends", category: .secrets, icon: "HeartHandshake", points: 50, hidden: true,
            name: AchievementText(en: "Best Friends Forever", fr: "Meilleurs amis pour la vie", ptBR: "Best Friends Forever"),
            description: AchievementText(en: "Pet your mascot five hundred times.", fr: "Flattez votre mascotte cinq cents fois.", ptBR: "Pet your mascot five hundred times."),
            hint: AchievementText(en: "Lots and lots of affection.", fr: "Beaucoup, beaucoup d'affection.", ptBR: "Lots and lots of affection."),
            rewards: [.skin(character: "trombi", skin: "molten", name: AchievementText(en: "Molten", fr: "Magma", ptBR: "Molten"), characterName: AchievementText(en: "Trombi", fr: "Trombi", ptBR: "Trombi"))]
        ),
        AchievementDefinition(
            id: "desk-buddy", category: .secrets, icon: "Monitor", points: 10, hidden: false,
            name: AchievementText(en: "Desk Buddy", fr: "Copain de bureau", ptBR: "Desk Buddy"),
            description: AchievementText(en: "Put a bot on your desktop.", fr: "Mettez un robot sur votre bureau.", ptBR: "Put a bot on your desktop."),
            hint: nil,
            rewards: [.title(id: "buddy", name: AchievementText(en: "Desk Buddy", fr: "Copain de bureau", ptBR: "Desk Buddy"))]
        ),
        AchievementDefinition(
            id: "trophy-case", category: .secrets, icon: "Trophy", points: 5, hidden: true,
            name: AchievementText(en: "Trophy Case", fr: "Vitrine à trophées", ptBR: "Trophy Case"),
            description: AchievementText(en: "Admire your achievements.", fr: "Admirez vos succès.", ptBR: "Admire your achievements."),
            hint: AchievementText(en: "Take a look at your trophies.", fr: "Jetez un œil à vos trophées.", ptBR: "Take a look at your trophies."),
            rewards: [.title(id: "collector", name: AchievementText(en: "Collector", fr: "Collectionneur", ptBR: "Collector"))]
        ),
        AchievementDefinition(
            id: "icon-swap", category: .secrets, icon: "AppWindow", points: 10, hidden: true,
            name: AchievementText(en: "New Look, Who Dis?", fr: "Nouvelle tête", ptBR: "New Look, Who Dis?"),
            description: AchievementText(en: "Change the app's icon.", fr: "Changez l'icône de l'application.", ptBR: "Change the app's icon."),
            hint: AchievementText(en: "The Dock could use a new face.", fr: "Le Dock aurait bien besoin d'une nouvelle tête.", ptBR: "The Dock could use a new face."),
            rewards: [.title(id: "stylist", name: AchievementText(en: "Stylist", fr: "Styliste", ptBR: "Stylist"))]
        ),
    ]
}
