// GENERATED by src/components/ios-mascot-export.test.ts from the desktop's
// Shapes engine (src/components/shape-art.ts, shape-engine.ts, shape-moves.ts):
// every number ShapeEngine.swift moves a shape with. Do not edit; regenerate
// with `UPDATE_IOS_MASCOT=1 pnpm vitest run src/components/ios-mascot-export.test.ts`.

/// The sixteen faces (`SHAPE_EXPRESSIONS`), in the desktop's order.
public enum ShapeExpression: String, CaseIterable, Sendable {
    case neutral
    case attentive
    case surprised
    case excited
    case happy
    case laughing
    case angry
    case sad
    case scared
    case suspicious
    case confused
    case curious
    case proud
    case shy
    case bored
    case sleepy
}

/// The fourteen one-shot moves (`SHAPE_MOVES`), in the editor's order.
public enum ShapeMove: String, CaseIterable, Sendable {
    case thinking
    case wink
    case wide
    case alert
    case notify
    case exclaim
    case sleep
    case egg
    case hexagon
    case play
    case orbit
    case swirl
    case burst
    case comet
}

public enum ShapeEngineData {
    /// How many radii make a body (`RADII_COUNT`).
    public static let radiiCount = 64
    /// Where the body sits in the 0..100 box and how many box units one R is (`BODY`).
    public static let bodyCenter: (x: Double, y: Double) = (x: 50, y: 50)
    public static let bodyUnit: Double = 40
    /// A change of shape, face or colour slides over this long, s (`MORPH_S`).
    public static let morphSeconds: Double = 0.45
    /// One breath, s, and how much it stretches the body (`BREATH_S`, `BREATH_AMOUNT`).
    public static let breathSeconds: Double = 3.4
    public static let breathAmount: Double = 0.005
    /// The blink schedule (`BLINK`).
    public static let blink = ShapeBlink(first: 1.4, minGap: 1.9, maxGap: 4.6, length: 0.18, closing: 0.45, doubleChance: 0.18, doubleAfter: 0.24, floor: 0.06)
    /// The gaze's turn toward a pointer (`HOVER`): degrees, and the ease, s.
    public static let hover: (yaw: Double, pitch: Double, turn: Double) = (yaw: 16, pitch: 13, turn: 0.85)
    /// The imaginary head's own turn and tilt, degrees (`HEAD`), and the face's drop (`FACE_DROP`).
    public static let head: (yaw: Double, pitch: Double) = (yaw: 28, pitch: 29)
    public static let faceDrop: Double = -7
    /// The clay light, R units from the body's middle (`CLAY_LIGHT`).
    public static let clayLight: (x: Double, y: Double, r: Double) = (x: -0.5, y: -0.62, r: 2.5)
    /// The five slow wander loops (`WANDER`): period, s, and reach, degrees.
    public static let wanderYaw: [ShapeLoop] = [.init(period: 10.9, reach: 5.2), .init(period: 3.9, reach: 1.5)]
    public static let wanderPitch: [ShapeLoop] = [.init(period: 8.7, reach: 4), .init(period: 4.6, reach: 1.2)]
    public static let wanderRoll: [ShapeLoop] = [.init(period: 13.1, reach: 2)]
    /// When an eye turned away hides (`EYE_FADE`) and the body it keeps around it, R (`EYE_MARGIN`).
    public static let eyeFade: (hidden: Double, over: Double) = (hidden: 0.02, over: 0.12)
    public static let eyeMargin: Double = 0.07

    /// The eight bodies, one radius (R) per angle, 0 up, clockwise (`SHAPE_RADII`).
    public static let radii: [MascotShape: [Double]] = [
        .circle: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        .blob: [1.0041, 1.0111, 1.017, 1.0218, 1.026, 1.0298, 1.0334, 1.0372, 1.0412, 1.0454, 1.0497, 1.0537, 1.0571, 1.0593, 1.06, 1.0587, 1.055, 1.0487, 1.0398, 1.0285, 1.0152, 1.0004, 0.985, 0.9699, 0.956, 0.9445, 0.9361, 0.9316, 0.9316, 0.9363, 0.9457, 0.9595, 0.977, 0.9972, 1.019, 1.0413, 1.0626, 1.0816, 1.0972, 1.1085, 1.1147, 1.1155, 1.1108, 1.101, 1.0866, 1.0686, 1.048, 1.026, 1.0039, 0.983, 0.9641, 0.9484, 0.9363, 0.9283, 0.9244, 0.9244, 0.9281, 0.9346, 0.9434, 0.9537, 0.9647, 0.9758, 0.9862, 0.9958],
        .squircle: [0.93, 0.9345, 0.9478, 0.9698, 0.9993, 1.034, 1.0688, 1.0957, 1.106, 1.0957, 1.0688, 1.034, 0.9993, 0.9698, 0.9478, 0.9345, 0.93, 0.9345, 0.9478, 0.9698, 0.9993, 1.034, 1.0688, 1.0957, 1.106, 1.0957, 1.0688, 1.034, 0.9993, 0.9698, 0.9478, 0.9345, 0.93, 0.9345, 0.9478, 0.9698, 0.9993, 1.034, 1.0688, 1.0957, 1.106, 1.0957, 1.0688, 1.034, 0.9993, 0.9698, 0.9478, 0.9345, 0.93, 0.9345, 0.9478, 0.9698, 0.9993, 1.034, 1.0688, 1.0957, 1.106, 1.0957, 1.0688, 1.034, 0.9993, 0.9698, 0.9478, 0.9345],
        .pill: [0.6, 0.6029, 0.6118, 0.627, 0.6494, 0.6803, 0.7216, 0.7734, 0.8242, 0.8712, 0.9138, 0.9511, 0.9824, 1.0073, 1.0254, 1.0363, 1.04, 1.0363, 1.0254, 1.0073, 0.9824, 0.9511, 0.9138, 0.8712, 0.8242, 0.7734, 0.7216, 0.6803, 0.6494, 0.627, 0.6118, 0.6029, 0.6, 0.6029, 0.6118, 0.627, 0.6494, 0.6803, 0.7216, 0.7734, 0.8242, 0.8712, 0.9138, 0.9511, 0.9824, 1.0073, 1.0254, 1.0363, 1.04, 1.0363, 1.0254, 1.0073, 0.9824, 0.9511, 0.9138, 0.8712, 0.8242, 0.7734, 0.7216, 0.6803, 0.6494, 0.627, 0.6118, 0.6029],
        .triangle: [1.05, 1.0352, 0.988, 0.9043, 0.8319, 0.7772, 0.7359, 0.7052, 0.6833, 0.6689, 0.6614, 0.6604, 0.6657, 0.6777, 0.697, 0.7246, 0.7621, 0.812, 0.8778, 0.9655, 1.0842, 1.1898, 1.2316, 1.2287, 1.18, 1.0867, 1.0103, 0.9525, 0.9092, 0.8778, 0.8565, 0.8441, 0.84, 0.8441, 0.8565, 0.8778, 0.9092, 0.9525, 1.0103, 1.0867, 1.18, 1.2287, 1.2316, 1.1898, 1.0842, 0.9655, 0.8778, 0.812, 0.7621, 0.7246, 0.697, 0.6777, 0.6657, 0.6604, 0.6614, 0.6689, 0.6833, 0.7052, 0.7359, 0.7772, 0.8319, 0.9043, 0.988, 1.0352],
        .hexagon: [0.9661, 0.9708, 0.985, 1.0096, 1.0457, 1.0779, 1.0714, 1.0323, 1.0002, 0.9792, 0.9682, 0.9666, 0.9745, 0.992, 1.0203, 1.0603, 1.08, 1.0603, 1.0203, 0.992, 0.9745, 0.9666, 0.9682, 0.9792, 1.0002, 1.0323, 1.0714, 1.0779, 1.0457, 1.0096, 0.985, 0.9708, 0.9661, 0.9708, 0.985, 1.0096, 1.0457, 1.0779, 1.0714, 1.0323, 1.0002, 0.9792, 0.9682, 0.9666, 0.9745, 0.992, 1.0203, 1.0603, 1.08, 1.0603, 1.0203, 0.992, 0.9745, 0.9666, 0.9682, 0.9792, 1.0002, 1.0323, 1.0714, 1.0779, 1.0457, 1.0096, 0.985, 0.9708],
        .cloud: [0.6847, 0.7307, 0.773, 0.8109, 0.8437, 0.871, 0.8921, 0.907, 0.9152, 0.9167, 0.9115, 0.8997, 0.8813, 0.8568, 0.8264, 0.8699, 0.9447, 1.0001, 1.0383, 1.0601, 1.0661, 1.0562, 1.0303, 0.988, 0.928, 0.8478, 0.7413, 0.7527, 0.7623, 0.77, 0.7755, 0.7789, 0.78, 0.7789, 0.7755, 0.77, 0.7623, 0.7527, 0.7413, 0.8478, 0.928, 0.988, 1.0303, 1.0562, 1.0661, 1.0601, 1.0383, 1.0001, 0.9447, 0.8699, 0.7701, 0.7666, 0.8009, 0.829, 0.8505, 0.8651, 0.8726, 0.8728, 0.8659, 0.8518, 0.8308, 0.8031, 0.7692, 0.7295],
        .drop: [1.1, 0.9985, 0.8861, 0.8034, 0.7414, 0.6944, 0.659, 0.6329, 0.6144, 0.6026, 0.5969, 0.597, 0.6029, 0.6149, 0.6336, 0.6557, 0.6788, 0.7028, 0.7273, 0.7521, 0.7769, 0.8013, 0.8251, 0.8479, 0.8694, 0.8892, 0.9071, 0.9227, 0.9358, 0.9463, 0.9539, 0.9585, 0.96, 0.9585, 0.9539, 0.9463, 0.9358, 0.9227, 0.9071, 0.8892, 0.8694, 0.8479, 0.8251, 0.8013, 0.7769, 0.7521, 0.7273, 0.7028, 0.6788, 0.6557, 0.6336, 0.6149, 0.6029, 0.597, 0.5969, 0.6026, 0.6144, 0.6329, 0.659, 0.6944, 0.7414, 0.8034, 0.8861, 0.9985],
    ]

    /// The bodies some moves turn into (`MOVE_RADII`).
    public static let moveRadii: [String: [Double]] = [
        "dot": [0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165, 0.165],
        "sleepDot": [0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16, 0.16],
        "burstDot": [0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166, 0.166],
        "cometDot": [0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13, 0.13],
        "egg": [1.02, 1.0142, 0.9979, 0.9741, 0.9462, 0.9172, 0.8893, 0.8638, 0.8417, 0.8232, 0.8085, 0.7978, 0.7908, 0.7876, 0.7881, 0.7922, 0.7999, 0.8108, 0.8251, 0.8422, 0.862, 0.884, 0.9074, 0.9315, 0.9554, 0.9783, 0.9992, 1.0175, 1.0328, 1.0447, 1.0532, 1.0583, 1.06, 1.0583, 1.0532, 1.0447, 1.0328, 1.0175, 0.9992, 0.9783, 0.9554, 0.9315, 0.9074, 0.884, 0.862, 0.8422, 0.8251, 0.8108, 0.7999, 0.7922, 0.7881, 0.7876, 0.7908, 0.7978, 0.8085, 0.8232, 0.8417, 0.8638, 0.8893, 0.9172, 0.9462, 0.9741, 0.9979, 1.0142],
        "hexagon": [1.08, 1.0603, 1.0203, 0.992, 0.9745, 0.9666, 0.9682, 0.9792, 1.0002, 1.0323, 1.0714, 1.0779, 1.0457, 1.0096, 0.985, 0.9708, 0.9661, 0.9708, 0.985, 1.0096, 1.0457, 1.0779, 1.0714, 1.0323, 1.0002, 0.9792, 0.9682, 0.9666, 0.9745, 0.992, 1.0203, 1.0603, 1.08, 1.0603, 1.0203, 0.992, 0.9745, 0.9666, 0.9682, 0.9792, 1.0002, 1.0323, 1.0714, 1.0779, 1.0457, 1.0096, 0.985, 0.9708, 0.9661, 0.9708, 0.985, 1.0096, 1.0457, 1.0779, 1.0714, 1.0323, 1.0002, 0.9792, 0.9682, 0.9666, 0.9745, 0.992, 1.0203, 1.0603],
        "triangle": [1.05, 1.0352, 0.988, 0.9043, 0.8319, 0.7772, 0.7359, 0.7052, 0.6833, 0.6689, 0.6614, 0.6604, 0.6657, 0.6777, 0.697, 0.7246, 0.7621, 0.812, 0.8778, 0.9655, 1.0842, 1.1898, 1.2316, 1.2287, 1.18, 1.0867, 1.0103, 0.9525, 0.9092, 0.8778, 0.8565, 0.8441, 0.84, 0.8441, 0.8565, 0.8778, 0.9092, 0.9525, 1.0103, 1.0867, 1.18, 1.2287, 1.2316, 1.1898, 1.0842, 0.9655, 0.8778, 0.812, 0.7621, 0.7246, 0.697, 0.6777, 0.6657, 0.6604, 0.6614, 0.6689, 0.6833, 0.7052, 0.7359, 0.7772, 0.8319, 0.9043, 0.988, 1.0352],
        "bar": [0.97, 0.9427, 0.7689, 0.5167, 0.392, 0.3182, 0.27, 0.2364, 0.2121, 0.194, 0.1804, 0.1701, 0.1624, 0.1567, 0.1529, 0.1507, 0.15, 0.1507, 0.1529, 0.1567, 0.1624, 0.1701, 0.1804, 0.194, 0.2121, 0.2364, 0.2615, 0.2824, 0.2995, 0.3129, 0.3224, 0.3281, 0.33, 0.3281, 0.3224, 0.3129, 0.2995, 0.2824, 0.2615, 0.2364, 0.2121, 0.194, 0.1804, 0.1701, 0.1624, 0.1567, 0.1529, 0.1507, 0.15, 0.1507, 0.1529, 0.1567, 0.1624, 0.1701, 0.1804, 0.194, 0.2121, 0.2364, 0.27, 0.3182, 0.392, 0.5167, 0.7689, 0.9427],
    ]

    /// The sixteen faces (`EXPRESSIONS`).
    public static let expressions: [ShapeExpression: ShapeFace] = [
        .neutral: .init(yaw: 0, pitch: 0, roll: -13, split: 15.5, left: .init(w: 0.25, h: 0.46, tilt: 0, open: 1), right: .init(w: 0.25, h: 0.46, tilt: 0, open: 1)),
        .attentive: .init(yaw: -2, pitch: 2, roll: -9, split: 15, left: .init(w: 0.26, h: 0.5, tilt: 0, open: 1), right: .init(w: 0.26, h: 0.5, tilt: 0, open: 1)),
        .surprised: .init(yaw: -3, pitch: 2, roll: -6, split: 18, left: .init(w: 0.44, h: 0.44, tilt: 0, open: 1), right: .init(w: 0.44, h: 0.44, tilt: 0, open: 1)),
        .excited: .init(yaw: -1, pitch: 4, roll: -10, split: 16.5, left: .init(w: 0.28, h: 0.54, tilt: 0, open: 1), right: .init(w: 0.28, h: 0.54, tilt: 0, open: 1)),
        .happy: .init(yaw: 0, pitch: 3, roll: -10, split: 16, left: .init(w: 0.34, h: 0.17, tilt: -10, open: 1), right: .init(w: 0.34, h: 0.17, tilt: 10, open: 1)),
        .laughing: .init(yaw: 0, pitch: 6, roll: -8, split: 17, left: .init(w: 0.31, h: 0.11, tilt: -18, open: 1), right: .init(w: 0.31, h: 0.11, tilt: 18, open: 1)),
        .angry: .init(yaw: -2, pitch: -3, roll: -12, split: 14.5, left: .init(w: 0.27, h: 0.19, tilt: 24, open: 1), right: .init(w: 0.27, h: 0.19, tilt: -24, open: 1)),
        .sad: .init(yaw: 2, pitch: -7, roll: -14, split: 15, left: .init(w: 0.2, h: 0.32, tilt: -18, open: 1), right: .init(w: 0.2, h: 0.32, tilt: 18, open: 1)),
        .scared: .init(yaw: -6, pitch: 1, roll: -8, split: 13, left: .init(w: 0.24, h: 0.38, tilt: 0, open: 1), right: .init(w: 0.24, h: 0.38, tilt: 0, open: 1)),
        .suspicious: .init(yaw: 7, pitch: -1, roll: -11, split: 15, left: .init(w: 0.29, h: 0.13, tilt: 6, open: 1), right: .init(w: 0.29, h: 0.13, tilt: 6, open: 1)),
        .confused: .init(yaw: 3, pitch: 1, roll: -20, split: 15.5, left: .init(w: 0.25, h: 0.46, tilt: 0, open: 1), right: .init(w: 0.25, h: 0.28, tilt: 10, open: 1)),
        .curious: .init(yaw: 5, pitch: 6, roll: -17, split: 15.5, left: .init(w: 0.26, h: 0.48, tilt: 0, open: 1), right: .init(w: 0.26, h: 0.48, tilt: 0, open: 1)),
        .proud: .init(yaw: -3, pitch: 9, roll: -6, split: 15, left: .init(w: 0.28, h: 0.12, tilt: 4, open: 1), right: .init(w: 0.28, h: 0.12, tilt: 4, open: 1)),
        .shy: .init(yaw: 10, pitch: -8, roll: -16, split: 13.5, left: .init(w: 0.18, h: 0.32, tilt: 0, open: 1), right: .init(w: 0.18, h: 0.32, tilt: 0, open: 1)),
        .bored: .init(yaw: 4, pitch: -3, roll: -12, split: 15, left: .init(w: 0.27, h: 0.14, tilt: 0, open: 1), right: .init(w: 0.27, h: 0.14, tilt: 0, open: 1)),
        .sleepy: .init(yaw: 1, pitch: -4, roll: -13, split: 15.5, left: .init(w: 0.26, h: 0.46, tilt: 0, open: 0.38), right: .init(w: 0.26, h: 0.46, tilt: 0, open: 0.38)),
    ]

    /// Each move's length and its slide in and out, s (`MOVE_TIMING`).
    public static let moveTiming: [ShapeMove: (duration: Double, morph: Double)] = [
        .thinking: (duration: 2.6, morph: 0.4),
        .wink: (duration: 1.6, morph: 0.3),
        .wide: (duration: 1.8, morph: 0.55),
        .alert: (duration: 2.4, morph: 0.45),
        .notify: (duration: 2.2, morph: 0.5),
        .exclaim: (duration: 2, morph: 0.45),
        .sleep: (duration: 2.4, morph: 0.5),
        .egg: (duration: 1.8, morph: 0.4),
        .hexagon: (duration: 1.6, morph: 0.4),
        .play: (duration: 2, morph: 0.5),
        .orbit: (duration: 3.4, morph: 0.6),
        .swirl: (duration: 1.3, morph: 0.3),
        .burst: (duration: 2.6, morph: 0.4),
        .comet: (duration: 2.4, morph: 0.45),
    ]

    /// The rings of Orbit and Swirl (`ORBIT_RINGS`, `SWIRL_RINGS`).
    public static let orbitRings: [ShapeRingSpec] = [
        .init(a: 1.24, tiltX: 64, tiltZ: -70, speed: 0.18, phase: 0, sweep: 1, hue: 340, hueSpan: 80, width: 0.05),
        .init(a: 1.31, tiltX: 71, tiltZ: -39, speed: 0.22, phase: 0.17, sweep: 1, hue: 38, hueSpan: 80, width: 0.065),
        .init(a: 1.38, tiltX: 78, tiltZ: -8, speed: 0.26, phase: 0.34, sweep: 1, hue: 96, hueSpan: 80, width: 0.08),
        .init(a: 1.24, tiltX: 85, tiltZ: 23, speed: 0.3, phase: 0.51, sweep: 1, hue: 154, hueSpan: 80, width: 0.05),
        .init(a: 1.31, tiltX: 92, tiltZ: 54, speed: 0.33999999999999997, phase: 0.68, sweep: 1, hue: 212, hueSpan: 80, width: 0.065),
        .init(a: 1.38, tiltX: 99, tiltZ: 85, speed: 0.38, phase: 0.8500000000000001, sweep: 1, hue: 270, hueSpan: 80, width: 0.08),
    ]
    public static let swirlRings: [ShapeRingSpec] = [
        .init(a: 1.36, tiltX: 74, tiltZ: -8, speed: 0.55, phase: 0, sweep: 0.86, hue: 20, hueSpan: 70, width: 0.06),
        .init(a: 1.22, tiltX: 66, tiltZ: 62, speed: 0.7, phase: 0.33, sweep: 0.8, hue: 120, hueSpan: 70, width: 0.055),
        .init(a: 1.3, tiltX: 70, tiltZ: -58, speed: 0.62, phase: 0.66, sweep: 0.8, hue: 210, hueSpan: 70, width: 0.05),
    ]

    /// The face each mood wears (`expressionForMood` in ShapeMascot.tsx).
    public static let moodExpression: [ShapeMood: ShapeExpression] = [
        .idle: .neutral,
        .thinking: .curious,
        .working: .attentive,
        .happy: .happy,
        .sleeping: .sleepy,
    ]
}
