// The catalog names its icons (shared/achievements-catalog.ts); this maps each
// name to its lucide component, explicitly, so the bundle carries only these.
// icons.test.ts checks every catalog icon is here.
import {
  AppWindow,
  Award,
  Bot,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Cog,
  Crown,
  Feather,
  FileArchive,
  Flame,
  FolderOpen,
  Gamepad2,
  Gem,
  Hand,
  Heart,
  HeartHandshake,
  Keyboard,
  Layers,
  Link,
  Medal,
  MessageCircle,
  MessageSquareMore,
  MessagesSquare,
  Monitor,
  Moon,
  MousePointerClick,
  Navigation,
  Network,
  Palette,
  Paperclip,
  Phone,
  PhoneCall,
  PhoneForwarded,
  Repeat,
  Rocket,
  Scale,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Shirt,
  Slash,
  Split,
  SquareTerminal,
  Timer,
  Trophy,
  Users,
  UsersRound,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const ACHIEVEMENT_ICONS: Readonly<Record<string, LucideIcon>> = {
  AppWindow,
  Award,
  Bot,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  Cog,
  Crown,
  Feather,
  FileArchive,
  Flame,
  FolderOpen,
  Gamepad2,
  Gem,
  Hand,
  Heart,
  HeartHandshake,
  Keyboard,
  Layers,
  Link,
  Medal,
  MessageCircle,
  MessageSquareMore,
  MessagesSquare,
  Monitor,
  Moon,
  MousePointerClick,
  Navigation,
  Network,
  Palette,
  Paperclip,
  Phone,
  PhoneCall,
  PhoneForwarded,
  Repeat,
  Rocket,
  Scale,
  Search,
  Send,
  Share2,
  ShieldCheck,
  Shirt,
  Slash,
  Split,
  SquareTerminal,
  Timer,
  Trophy,
  Users,
  UsersRound,
  Zap,
};

export function achievementIcon(name: string): LucideIcon {
  return ACHIEVEMENT_ICONS[name] ?? Trophy;
}
