// The achievements catalog: pure data, checked by shared/achievements-catalog.test.ts.
//
// Each one teaches a habit that makes Sagax more useful, in the order a
// person meets them: onboarding, then productivity, power use, voice,
// working with others, coming back (streaks), mastery tiers, and a few
// secrets for the curious. Points are Gamerscore-like (5, 10, 20, 50, 100)
// and set the rarity; a skin reward's own rarity matches the points it costs
// (Rare 10 or 20, Epic 20 or 50, Legendary 50 or 100).
//
// Every skin above Common and both locked characters (Trombi, Bunbu) are a
// reward of exactly one achievement. Trombi comes only from its command
// (/hibou98), never from points. An id is stored per person: never rename
// one; retire it by keeping it in the list.
import type { AchievementDefinition } from "./achievements.ts";

const skin = (character: "owl" | "shape" | "trombi" | "bunbu", id: string) => ({ kind: "skin", character, skin: id }) as const;
const title = (id: string, en: string, fr: string) => ({ kind: "title", id, name: { en, fr } }) as const;

export const ACHIEVEMENTS: readonly AchievementDefinition[] = [
  /* ------------------------------------------------------------ onboarding */
  {
    id: "first-words",
    category: "onboarding",
    name: { en: "First Words", fr: "Premiers mots" },
    description: { en: "Send your first message to a bot.", fr: "Envoyez votre premier message à un robot." },
    icon: "MessageCircle",
    points: 5,
    rule: { kind: "count", event: "message.sent", target: 1 },
    rewards: [title("rookie", "Rookie", "Recrue")],
  },
  {
    id: "hello-bot",
    category: "onboarding",
    name: { en: "It's Alive!", fr: "Il est vivant!" },
    description: { en: "Create your first bot.", fr: "Créez votre premier robot." },
    icon: "Bot",
    points: 10,
    rule: { kind: "count", event: "bot.created", target: 1 },
    rewards: [skin("shape", "outline")],
  },
  {
    id: "makeover",
    category: "onboarding",
    name: { en: "Makeover", fr: "Relooking" },
    description: { en: "Change a bot's look: its character, color or skin.", fr: "Changez l'allure d'un robot : son personnage, sa couleur ou son skin." },
    icon: "Palette",
    points: 10,
    rule: { kind: "count", event: "bot.customized", target: 1 },
    rewards: [skin("owl", "gold")],
  },
  {
    id: "right-hand",
    category: "onboarding",
    name: { en: "Right Hand", fr: "Bras droit" },
    description: { en: "Choose a Primary Bot.", fr: "Choisissez un Robot principal." },
    icon: "Crown",
    points: 20,
    rule: { kind: "count", event: "bot.primary", target: 1 },
    rewards: [skin("owl", "frost")],
  },
  {
    id: "dressing-room",
    category: "onboarding",
    name: { en: "Dressing Room", fr: "Salle d'essayage" },
    description: { en: "Dress bots as three different characters.", fr: "Habillez des robots en trois personnages différents." },
    icon: "Shirt",
    points: 20,
    rule: { kind: "distinct", event: "bot.customized", target: 3 },
    rewards: [skin("shape", "gold")],
  },
  {
    id: "small-family",
    category: "onboarding",
    name: { en: "Small Family", fr: "Petite famille" },
    description: { en: "Create three bots.", fr: "Créez trois robots." },
    icon: "Users",
    points: 20,
    rule: { kind: "count", event: "bot.created", target: 3 },
    rewards: [{ kind: "character", character: "bunbu" }],
  },

  /* ---------------------------------------------------------- productivity */
  {
    id: "on-schedule",
    category: "productivity",
    name: { en: "On Schedule", fr: "Réglé comme une horloge" },
    description: { en: "Create your first routine.", fr: "Créez votre première routine." },
    icon: "CalendarClock",
    points: 10,
    rule: { kind: "count", event: "routine.created", target: 1 },
    rewards: [skin("bunbu", "velvet")],
  },
  {
    id: "routine-five",
    category: "productivity",
    name: { en: "Automation Fan", fr: "Fan d'automatisation" },
    description: { en: "Create five routines.", fr: "Créez cinq routines." },
    icon: "Repeat",
    points: 20,
    rule: { kind: "count", event: "routine.created", target: 5 },
    rewards: [title("automator", "Automator", "Automatiseur")],
  },
  {
    id: "clockwork",
    category: "productivity",
    name: { en: "Clockwork", fr: "Mécanique de précision" },
    description: { en: "Have your routines run on seven different days.", fr: "Faites rouler vos routines sept jours différents." },
    icon: "Timer",
    points: 50,
    rule: { kind: "days", event: "routine.ran", target: 7 },
    rewards: [skin("owl", "chrome")],
  },
  {
    id: "well-oiled",
    category: "productivity",
    name: { en: "Well-Oiled Machine", fr: "Machine bien huilée" },
    description: { en: "Have your routines complete fifty runs.", fr: "Faites compléter cinquante exécutions à vos routines." },
    icon: "Cog",
    points: 100,
    rule: { kind: "count", event: "routine.ran", target: 50 },
    rewards: [skin("shape", "molten")],
  },
  {
    id: "gatekeeper",
    category: "productivity",
    name: { en: "Gatekeeper", fr: "Gardien" },
    description: { en: "Answer a bot's approval request.", fr: "Répondez à une demande d'approbation d'un robot." },
    icon: "ShieldCheck",
    points: 5,
    rule: { kind: "count", event: "approval.answered", target: 1 },
    rewards: [title("gatekeeper", "Gatekeeper", "Gardien")],
  },
  {
    id: "trusted-judge",
    category: "productivity",
    name: { en: "Trusted Judge", fr: "Juge de confiance" },
    description: { en: "Answer twenty-five approval requests.", fr: "Répondez à vingt-cinq demandes d'approbation." },
    icon: "Scale",
    points: 20,
    rule: { kind: "count", event: "approval.answered", target: 25 },
    rewards: [skin("shape", "neon")],
  },
  {
    id: "slash-and-learn",
    category: "productivity",
    name: { en: "Slash and Learn", fr: "Barre oblique" },
    description: { en: "Run a slash command from the composer.", fr: "Lancez une commande « / » depuis la zone de saisie." },
    icon: "Slash",
    points: 5,
    rule: { kind: "count", event: "message.slash", target: 1 },
    rewards: [title("commander", "Commander", "Commandant")],
  },
  {
    id: "command-collector",
    category: "productivity",
    name: { en: "Command Collector", fr: "Collectionneur de commandes" },
    description: { en: "Use five different slash commands.", fr: "Utilisez cinq commandes « / » différentes." },
    icon: "SquareTerminal",
    points: 20,
    rule: { kind: "distinct", event: "message.slash", target: 5 },
    rewards: [skin("shape", "circuit")],
  },
  {
    id: "paperclip",
    category: "productivity",
    name: { en: "See Attached", fr: "Voir pièce jointe" },
    description: { en: "Attach a file or an image to a message.", fr: "Joignez un fichier ou une image à un message." },
    icon: "Paperclip",
    points: 10,
    rule: { kind: "count", event: "message.attachment", target: 1 },
    rewards: [skin("bunbu", "gold")],
  },
  {
    id: "zip-it",
    category: "productivity",
    name: { en: "Zip It", fr: "Tout compressé" },
    description: { en: "Hand a bot a .zip archive.", fr: "Donnez une archive .zip à un robot." },
    icon: "FileArchive",
    points: 10,
    rule: { kind: "count", event: "message.zip", target: 1 },
    rewards: [skin("trombi", "gold")],
  },
  {
    id: "librarian",
    category: "productivity",
    name: { en: "Librarian", fr: "Bibliothécaire" },
    description: { en: "Open a bot's Library to see its files.", fr: "Ouvrez la Bibliothèque d'un robot pour voir ses fichiers." },
    icon: "FolderOpen",
    points: 5,
    rule: { kind: "count", event: "files.opened", target: 1 },
    rewards: [title("librarian", "Librarian", "Bibliothécaire")],
  },
  {
    id: "chatterbox",
    category: "productivity",
    name: { en: "Chatterbox", fr: "Moulin à paroles" },
    description: { en: "Send one hundred messages.", fr: "Envoyez cent messages." },
    icon: "MessagesSquare",
    points: 20,
    rule: { kind: "count", event: "message.sent", target: 100 },
    rewards: [skin("bunbu", "neon")],
  },
  {
    id: "wordsmith",
    category: "productivity",
    name: { en: "Wordsmith", fr: "Plume d'or" },
    description: { en: "Send one thousand messages.", fr: "Envoyez mille messages." },
    icon: "Feather",
    points: 50,
    rule: { kind: "count", event: "message.sent", target: 1000 },
    rewards: [skin("owl", "inferno")],
  },

  /* ----------------------------------------------------------------- power */
  {
    id: "multitasker",
    category: "power",
    name: { en: "Multitasker", fr: "Multitâche" },
    description: { en: "Send a request as a parallel task while the bot is busy.", fr: "Envoyez une demande en tâche parallèle pendant que le robot travaille." },
    icon: "Split",
    points: 20,
    rule: { kind: "count", event: "message.parallel", target: 1 },
    rewards: [skin("shape", "chrome")],
  },
  {
    id: "juggler",
    category: "power",
    name: { en: "Juggler", fr: "Jongleur" },
    description: { en: "Start ten parallel tasks.", fr: "Lancez dix tâches parallèles." },
    icon: "Layers",
    points: 50,
    rule: { kind: "count", event: "message.parallel", target: 10 },
    rewards: [skin("shape", "holo")],
  },
  {
    id: "delegator",
    category: "power",
    name: { en: "Delegator", fr: "Délégateur" },
    description: { en: "Have a bot of yours hand work to a sub-agent.", fr: "Faites confier du travail à un sous-agent par un de vos robots." },
    icon: "Network",
    points: 20,
    rule: { kind: "count", event: "subagent.used", target: 1 },
    rewards: [skin("trombi", "neon")],
  },
  {
    id: "hands-on",
    category: "power",
    name: { en: "Hands On", fr: "Aux commandes" },
    description: { en: "Take control of a bot's computer.", fr: "Prenez le contrôle de l'ordinateur d'un robot." },
    icon: "MousePointerClick",
    points: 20,
    rule: { kind: "count", event: "computer.control", target: 1 },
    rewards: [skin("bunbu", "chrome")],
  },
  {
    id: "autopilot",
    category: "power",
    name: { en: "Autopilot", fr: "Pilote automatique" },
    description: { en: "Let a bot pick the right computer by itself (Works on: Auto).", fr: "Laissez un robot choisir le bon ordinateur lui-même (Travaille sur : Auto)." },
    icon: "Navigation",
    points: 20,
    rule: { kind: "count", event: "computer.auto", target: 1 },
    rewards: [skin("trombi", "chrome")],
  },
  {
    id: "great-power",
    category: "power",
    name: { en: "With Great Power", fr: "Grands pouvoirs" },
    description: { en: "Grant a bot Full access, then bring it back to Ask.", fr: "Accordez l'Accès complet à un robot, puis ramenez-le à Demander." },
    icon: "Zap",
    points: 50,
    rule: { kind: "all", events: ["fullaccess.granted", "fullaccess.revoked"] },
    rewards: [skin("owl", "holo")],
  },
  {
    id: "palette",
    category: "power",
    name: { en: "Quick Finder", fr: "Trouve-tout" },
    description: { en: "Open the command palette.", fr: "Ouvrez la palette de commandes." },
    icon: "Search",
    points: 5,
    rule: { kind: "count", event: "palette.opened", target: 1 },
    rewards: [{ kind: "appIcon", id: "glyph:cube" }],
  },
  {
    id: "keyboard-ninja",
    category: "power",
    name: { en: "Keyboard Ninja", fr: "Ninja du clavier" },
    description: { en: "Open the keyboard shortcuts.", fr: "Ouvrez les raccourcis clavier." },
    icon: "Keyboard",
    points: 5,
    rule: { kind: "count", event: "shortcuts.opened", target: 1 },
    rewards: [{ kind: "appIcon", id: "glyph:spark" }],
  },

  /* ----------------------------------------------------------------- voice */
  {
    id: "first-call",
    category: "voice",
    name: { en: "On the Line", fr: "En ligne" },
    description: { en: "Call a bot with voice mode.", fr: "Appelez un robot en mode voix." },
    icon: "Phone",
    points: 20,
    rule: { kind: "count", event: "voice.call", target: 1 },
    rewards: [skin("owl", "neon")],
  },
  {
    id: "long-call",
    category: "voice",
    name: { en: "Long Distance", fr: "Interurbain" },
    description: { en: "Stay on a voice call for ten minutes.", fr: "Restez dix minutes en appel vocal." },
    icon: "PhoneCall",
    points: 20,
    rule: { kind: "max", event: "voice.minutes", target: 10 },
    rewards: [skin("bunbu", "crystal")],
  },
  {
    id: "polite-interrupt",
    category: "voice",
    name: { en: "Excuse Me", fr: "Pardon de vous interrompre" },
    description: { en: "Interrupt a bot mid-sentence on a call.", fr: "Interrompez un robot au milieu d'une phrase pendant un appel." },
    icon: "Hand",
    points: 10,
    rule: { kind: "count", event: "voice.interrupt", target: 1 },
    rewards: [title("polite", "Polite", "Poli")],
  },
  {
    id: "hotline",
    category: "voice",
    name: { en: "Hotline", fr: "Ligne directe" },
    description: { en: "Make ten voice calls.", fr: "Faites dix appels vocaux." },
    icon: "PhoneForwarded",
    points: 50,
    rule: { kind: "distinct", event: "voice.call", target: 10 },
    rewards: [skin("bunbu", "holo")],
  },

  /* --------------------------------------------------------- collaboration */
  {
    id: "sharing-is-caring",
    category: "collaboration",
    name: { en: "Sharing Is Caring", fr: "Partager, c'est donner" },
    description: { en: "Share a bot with someone.", fr: "Partagez un robot avec quelqu'un." },
    icon: "Share2",
    points: 20,
    rule: { kind: "count", event: "bot.shared", target: 1 },
    rewards: [skin("shape", "crystal")],
  },
  {
    id: "dream-team",
    category: "collaboration",
    name: { en: "Dream Team", fr: "Équipe de rêve" },
    description: { en: "Talk in a group with another person and two bots.", fr: "Discutez dans un groupe avec une autre personne et deux robots." },
    icon: "UsersRound",
    points: 50,
    rule: { kind: "count", event: "group.mixed", target: 1 },
    rewards: [skin("shape", "galaxy")],
  },
  {
    id: "direct-line",
    category: "collaboration",
    name: { en: "Direct Line", fr: "Message direct" },
    description: { en: "Send a direct message to a colleague.", fr: "Envoyez un message direct à un collègue." },
    icon: "Send",
    points: 10,
    rule: { kind: "count", event: "dm.sent", target: 1 },
    rewards: [title("connector", "Connector", "Rassembleur")],
  },
  {
    id: "group-chat",
    category: "collaboration",
    name: { en: "Round Table", fr: "Table ronde" },
    description: { en: "Send ten messages in groups.", fr: "Envoyez dix messages dans des groupes." },
    icon: "MessageSquareMore",
    points: 10,
    rule: { kind: "count", event: "group.message", target: 10 },
    rewards: [title("host", "Host", "Animateur")],
  },

  /* --------------------------------------------------------------- streaks */
  {
    id: "three-day",
    category: "streaks",
    name: { en: "Warming Up", fr: "On se réchauffe" },
    description: { en: "Use Sagax three days in a row.", fr: "Utilisez Sagax trois jours de suite." },
    icon: "Flame",
    points: 10,
    rule: { kind: "streak", target: 3 },
    rewards: [title("regular", "Regular", "Habitué")],
  },
  {
    id: "week-streak",
    category: "streaks",
    name: { en: "Week Warrior", fr: "Guerrier de la semaine" },
    description: { en: "Use Sagax seven days in a row.", fr: "Utilisez Sagax sept jours de suite." },
    icon: "CalendarCheck",
    points: 20,
    rule: { kind: "streak", target: 7 },
    rewards: [skin("trombi", "glitch")],
  },
  {
    id: "month-streak",
    category: "streaks",
    name: { en: "Unstoppable", fr: "Inarrêtable" },
    description: { en: "Use Sagax thirty days in a row.", fr: "Utilisez Sagax trente jours de suite." },
    icon: "Rocket",
    points: 100,
    rule: { kind: "streak", target: 30 },
    rewards: [skin("owl", "galaxy")],
  },
  {
    id: "regular",
    category: "streaks",
    name: { en: "Part of the Team", fr: "Membre de l'équipe" },
    description: { en: "Use Sagax on twenty different days.", fr: "Utilisez Sagax vingt jours différents." },
    icon: "CalendarDays",
    points: 50,
    rule: { kind: "activeDays", target: 20 },
    rewards: [skin("bunbu", "molten")],
  },

  /* --------------------------------------------------------------- mastery */
  {
    id: "bronze",
    category: "mastery",
    name: { en: "Bronze", fr: "Bronze" },
    description: { en: "Earn 100 points.", fr: "Obtenez 100 points." },
    icon: "Medal",
    points: 10,
    rule: { kind: "points", target: 100 },
    rewards: [title("bronze", "Bronze Operator", "Opérateur bronze")],
  },
  {
    id: "silver",
    category: "mastery",
    name: { en: "Silver", fr: "Argent" },
    description: { en: "Earn 300 points.", fr: "Obtenez 300 points." },
    icon: "Award",
    points: 20,
    rule: { kind: "points", target: 300 },
    rewards: [title("silver", "Silver Operator", "Opérateur argent")],
  },
  {
    id: "gold-tier",
    category: "mastery",
    name: { en: "Gold", fr: "Or" },
    description: { en: "Earn 600 points.", fr: "Obtenez 600 points." },
    icon: "Trophy",
    points: 50,
    rule: { kind: "points", target: 600 },
    rewards: [skin("trombi", "holo")],
  },
  {
    id: "platinum",
    category: "mastery",
    name: { en: "Platinum", fr: "Platine" },
    description: { en: "Unlock every achievement that is not a secret.", fr: "Débloquez tous les succès qui ne sont pas secrets." },
    icon: "Gem",
    points: 100,
    rule: { kind: "completion" },
    rewards: [skin("bunbu", "galaxy"), title("platinum", "Platinum Sage", "Sage platine")],
  },

  /* --------------------------------------------------------------- secrets */
  {
    id: "trombi-summoned",
    category: "secrets",
    name: { en: "It Looks Like You're Writing", fr: "On dirait que vous écrivez" },
    description: { en: "Summon Trombi with its command. Trombi is yours for good.", fr: "Invoquez Trombi avec sa commande. Trombi est à vous pour de bon." },
    icon: "Paperclip",
    points: 20,
    hidden: true,
    rule: { kind: "count", event: "trombi.summoned", target: 1 },
    rewards: [{ kind: "character", character: "trombi" }],
  },
  {
    id: "konami",
    category: "secrets",
    name: { en: "Up Up Down Down", fr: "Haut haut bas bas" },
    description: { en: "Enter the old cheat code.", fr: "Entrez le vieux code de triche." },
    icon: "Gamepad2",
    points: 50,
    hidden: true,
    rule: { kind: "count", event: "konami", target: 1 },
    rewards: [skin("owl", "lightning")],
  },
  {
    id: "night-owl",
    category: "secrets",
    name: { en: "Night Owl", fr: "Oiseau de nuit" },
    description: { en: "Talk to your desktop mascot between midnight and 1 a.m.", fr: "Parlez à votre mascotte de bureau entre minuit et 1 h." },
    icon: "Moon",
    points: 50,
    hidden: true,
    rule: { kind: "count", event: "mascot.midnight", target: 1 },
    rewards: [skin("owl", "spirit")],
  },
  {
    id: "good-bot",
    category: "secrets",
    name: { en: "Who's a Good Bot?", fr: "Qui est un bon robot?" },
    description: { en: "Pet your mascot fifty times.", fr: "Flattez votre mascotte cinquante fois." },
    icon: "Heart",
    points: 10,
    hidden: true,
    rule: { kind: "count", event: "mascot.pet", target: 50 },
    rewards: [title("petter", "Bot Whisperer", "Charmeur de robots")],
  },
  {
    id: "best-friends",
    category: "secrets",
    name: { en: "Best Friends Forever", fr: "Meilleurs amis pour la vie" },
    description: { en: "Pet your mascot five hundred times.", fr: "Flattez votre mascotte cinq cents fois." },
    icon: "HeartHandshake",
    points: 50,
    hidden: true,
    rule: { kind: "count", event: "mascot.pet", target: 500 },
    rewards: [skin("trombi", "molten")],
  },
  {
    id: "desk-buddy",
    category: "secrets",
    name: { en: "Desk Buddy", fr: "Copain de bureau" },
    description: { en: "Put a bot on your desktop.", fr: "Mettez un robot sur votre bureau." },
    icon: "Monitor",
    points: 10,
    rule: { kind: "count", event: "mascot.floated", target: 1 },
    rewards: [title("buddy", "Desk Buddy", "Copain de bureau")],
  },
  {
    id: "trophy-case",
    category: "secrets",
    name: { en: "Trophy Case", fr: "Vitrine à trophées" },
    description: { en: "Admire your achievements.", fr: "Admirez vos succès." },
    icon: "Trophy",
    points: 5,
    hidden: true,
    rule: { kind: "count", event: "achievements.viewed", target: 1 },
    rewards: [title("collector", "Collector", "Collectionneur")],
  },
  {
    id: "icon-swap",
    category: "secrets",
    name: { en: "New Look, Who Dis?", fr: "Nouvelle tête" },
    description: { en: "Change the app's icon.", fr: "Changez l'icône de l'application." },
    icon: "AppWindow",
    points: 10,
    hidden: true,
    rule: { kind: "count", event: "appicon.changed", target: 1 },
    rewards: [title("stylist", "Stylist", "Styliste")],
  },
];

const byId = new Map(ACHIEVEMENTS.map((item) => [item.id, item]));

export function achievementById(id: string): AchievementDefinition | undefined {
  return byId.get(id);
}
