// The achievements catalog: pure data, checked by shared/achievements-catalog.test.ts.
//
// Each one teaches a habit that makes Sagax more useful, in the order a
// person meets them: onboarding, then productivity, power use, voice,
// working with others, coming back (streaks), the Mastery tier, the points
// tiers, and a few secrets for the curious. Points are Gamerscore-like (5,
// 10, 20, 50, 100) and set the rarity; a skin reward's own rarity matches the
// points it costs (Rare 10 or 20, Epic 20 or 50, Legendary 50 or 100).
//
// The Mastery tier (category "mastery", docs/achievements.md) is harder: 100
// to 300 points, each proving real use of AI and of Sagax, measured by the
// server (shared/achievements-mastery.ts). Its rewards are the four Mastery
// characters and their skins, read from shared/mascot-unlocks.ts, so a
// character that has not landed yet is already a reward.
//
// Every skin above Common and every character except the owl is a reward of
// exactly one achievement. Shapes comes from linking a Grok account. Trombi
// comes only from its hidden command, never from points, and that command is
// not written down. An id is stored per person: never rename one; retire it
// by keeping it in the list.
import type { AchievementDefinition, AchievementReward } from "./achievements.ts";
import type { MasteryMetric } from "./achievements-mastery.ts";
import { masteryRewards } from "./mascot-unlocks.ts";

const skin = (character: "owl" | "shape" | "trombi" | "bunbu" | "shiba", id: string) => ({ kind: "skin", character, skin: id }) as const;
const title = (id: string, en: string, fr: string) => ({ kind: "title", id, name: { en, fr } }) as const;
const mastery = (id: string, metric: MasteryMetric, target: number) => ({
  id,
  category: "mastery" as const,
  rule: { kind: "mastery" as const, metric, target },
  rewards: masteryRewards(id) as AchievementReward[],
});

const CATALOG: readonly AchievementDefinition[] = [
  /* ------------------------------------------------------------ onboarding */
  {
    id: "first-words",
    category: "onboarding",
    name: { en: "First Words", fr: "Premiers mots" },
    description: { en: "Send your first message to a bot.", fr: "Envoyez votre premier message à un robot." },
    icon: "MessageCircle",
    points: 5,
    rule: { kind: "count", event: "message.sent", target: 1 },
    rewards: [title("rookie", "Rookie", "Recrue")],
  },
  {
    id: "hello-bot",
    category: "onboarding",
    name: { en: "It's Alive!", fr: "Il est vivant!" },
    description: { en: "Create your first bot.", fr: "Créez votre premier robot." },
    icon: "Bot",
    points: 10,
    rule: { kind: "count", event: "bot.created", target: 1 },
    rewards: [skin("shape", "outline")],
  },
  {
    id: "grok-linked",
    category: "onboarding",
    name: { en: "Grok Linked", fr: "Compte Grok lié" },
    description: { en: "Sign in to Grok, or save your own xAI key.", fr: "Connectez-vous à Grok, ou enregistrez votre propre clé xAI." },
    icon: "Link",
    points: 10,
    rule: { kind: "count", event: "grok.linked", target: 1 },
    rewards: [{ kind: "character", character: "shape" }],
  },
  {
    id: "makeover",
    category: "onboarding",
    name: { en: "Makeover", fr: "Relooking" },
    description: { en: "Change a bot's look: its character, color or skin.", fr: "Changez l'allure d'un robot : son personnage, sa couleur ou son skin." },
    icon: "Palette",
    points: 10,
    rule: { kind: "count", event: "bot.customized", target: 1 },
    rewards: [skin("owl", "gold"), skin("shiba", "gold")],
  },
  {
    id: "right-hand",
    category: "onboarding",
    name: { en: "Right Hand", fr: "Bras droit" },
    description: { en: "Choose a Primary Bot.", fr: "Choisissez un Robot principal." },
    icon: "Crown",
    points: 20,
    rule: { kind: "count", event: "bot.primary", target: 1 },
    rewards: [skin("owl", "frost"), skin("shiba", "neon")],
  },
  {
    id: "dressing-room",
    category: "onboarding",
    name: { en: "Dressing Room", fr: "Salle d'essayage" },
    description: { en: "Dress bots as three different characters.", fr: "Habillez des robots en trois personnages différents." },
    icon: "Shirt",
    points: 20,
    rule: { kind: "distinct", event: "bot.customized", target: 3 },
    rewards: [skin("shape", "gold")],
  },
  {
    id: "small-family",
    category: "onboarding",
    name: { en: "Small Family", fr: "Petite famille" },
    description: { en: "Create three bots.", fr: "Créez trois robots." },
    icon: "Users",
    points: 20,
    rule: { kind: "count", event: "bot.created", target: 3 },
    rewards: [{ kind: "character", character: "bunbu" }],
  },

  /* ---------------------------------------------------------- productivity */
  {
    id: "on-schedule",
    category: "productivity",
    name: { en: "On Schedule", fr: "Réglé comme une horloge" },
    description: { en: "Create your first routine.", fr: "Créez votre première routine." },
    icon: "CalendarClock",
    points: 10,
    rule: { kind: "count", event: "routine.created", target: 1 },
    rewards: [skin("bunbu", "velvet")],
  },
  {
    id: "routine-five",
    category: "productivity",
    name: { en: "Automation Fan", fr: "Fan d'automatisation" },
    description: { en: "Create five routines.", fr: "Créez cinq routines." },
    icon: "Repeat",
    points: 20,
    rule: { kind: "count", event: "routine.created", target: 5 },
    rewards: [title("automator", "Automator", "Automatiseur"), skin("shiba", "chrome")],
  },
  {
    id: "clockwork",
    category: "productivity",
    name: { en: "Clockwork", fr: "Mécanique de précision" },
    description: { en: "Have your routines run on seven different days.", fr: "Faites rouler vos routines sept jours différents." },
    icon: "Timer",
    points: 50,
    rule: { kind: "days", event: "routine.ran", target: 7 },
    rewards: [skin("owl", "chrome"), skin("shiba", "molten")],
  },
  {
    id: "well-oiled",
    category: "productivity",
    name: { en: "Well-Oiled Machine", fr: "Machine bien huilée" },
    description: { en: "Have your routines complete fifty runs.", fr: "Faites compléter cinquante exécutions à vos routines." },
    icon: "Cog",
    points: 100,
    rule: { kind: "count", event: "routine.ran", target: 50 },
    rewards: [skin("shape", "molten")],
  },
  {
    id: "gatekeeper",
    category: "productivity",
    name: { en: "Gatekeeper", fr: "Gardien" },
    description: { en: "Answer a bot's approval request.", fr: "Répondez à une demande d'approbation d'un robot." },
    icon: "ShieldCheck",
    points: 5,
    rule: { kind: "count", event: "approval.answered", target: 1 },
    rewards: [title("gatekeeper", "Gatekeeper", "Gardien")],
  },
  {
    id: "trusted-judge",
    category: "productivity",
    name: { en: "Trusted Judge", fr: "Juge de confiance" },
    description: { en: "Answer twenty-five approval requests.", fr: "Répondez à vingt-cinq demandes d'approbation." },
    icon: "Scale",
    points: 20,
    rule: { kind: "count", event: "approval.answered", target: 25 },
    rewards: [skin("shape", "neon")],
  },
  {
    id: "slash-and-learn",
    category: "productivity",
    name: { en: "Slash and Learn", fr: "Barre oblique" },
    description: { en: "Run a slash command from the composer.", fr: "Lancez une commande « / » depuis la zone de saisie." },
    icon: "Slash",
    points: 5,
    rule: { kind: "count", event: "message.slash", target: 1 },
    rewards: [title("commander", "Commander", "Commandant")],
  },
  {
    id: "command-collector",
    category: "productivity",
    name: { en: "Command Collector", fr: "Collectionneur de commandes" },
    description: { en: "Use five different slash commands.", fr: "Utilisez cinq commandes « / » différentes." },
    icon: "SquareTerminal",
    points: 20,
    rule: { kind: "distinct", event: "message.slash", target: 5 },
    rewards: [skin("shape", "circuit")],
  },
  {
    id: "paperclip",
    category: "productivity",
    name: { en: "See Attached", fr: "Voir pièce jointe" },
    description: { en: "Attach a file or an image to a message.", fr: "Joignez un fichier ou une image à un message." },
    icon: "Paperclip",
    points: 10,
    rule: { kind: "count", event: "message.attachment", target: 1 },
    rewards: [skin("bunbu", "gold")],
  },
  {
    id: "zip-it",
    category: "productivity",
    name: { en: "Zip It", fr: "Tout compressé" },
    description: { en: "Hand a bot a .zip archive.", fr: "Donnez une archive .zip à un robot." },
    icon: "FileArchive",
    points: 10,
    rule: { kind: "count", event: "message.zip", target: 1 },
    rewards: [skin("trombi", "gold")],
  },
  {
    id: "librarian",
    category: "productivity",
    name: { en: "Librarian", fr: "Bibliothécaire" },
    description: { en: "Open a bot's Library to see its files.", fr: "Ouvrez la Bibliothèque d'un robot pour voir ses fichiers." },
    icon: "FolderOpen",
    points: 5,
    rule: { kind: "count", event: "files.opened", target: 1 },
    rewards: [title("librarian", "Librarian", "Bibliothécaire")],
  },
  {
    id: "chatterbox",
    category: "productivity",
    name: { en: "Chatterbox", fr: "Moulin à paroles" },
    description: { en: "Send one hundred messages.", fr: "Envoyez cent messages." },
    icon: "MessagesSquare",
    points: 20,
    rule: { kind: "count", event: "message.sent", target: 100 },
    rewards: [skin("bunbu", "neon")],
  },
  {
    id: "wordsmith",
    category: "productivity",
    name: { en: "Wordsmith", fr: "Plume d'or" },
    description: { en: "Send one thousand messages.", fr: "Envoyez mille messages." },
    icon: "Feather",
    points: 50,
    rule: { kind: "count", event: "message.sent", target: 1000 },
    rewards: [skin("owl", "inferno")],
  },

  /* ----------------------------------------------------------------- power */
  {
    id: "multitasker",
    category: "power",
    name: { en: "Multitasker", fr: "Multitâche" },
    description: { en: "Send a request as a parallel task while the bot is busy.", fr: "Envoyez une demande en tâche parallèle pendant que le robot travaille." },
    icon: "Split",
    points: 20,
    rule: { kind: "count", event: "message.parallel", target: 1 },
    rewards: [skin("shape", "chrome")],
  },
  {
    id: "juggler",
    category: "power",
    name: { en: "Juggler", fr: "Jongleur" },
    description: { en: "Start ten parallel tasks.", fr: "Lancez dix tâches parallèles." },
    icon: "Layers",
    points: 50,
    rule: { kind: "count", event: "message.parallel", target: 10 },
    rewards: [skin("shape", "holo")],
  },
  {
    id: "delegator",
    category: "power",
    name: { en: "Delegator", fr: "Délégateur" },
    description: { en: "Have a bot of yours hand work to a sub-agent.", fr: "Faites confier du travail à un sous-agent par un de vos robots." },
    icon: "Network",
    points: 20,
    rule: { kind: "count", event: "subagent.used", target: 1 },
    rewards: [skin("trombi", "neon")],
  },
  {
    id: "hands-on",
    category: "power",
    name: { en: "Hands On", fr: "Aux commandes" },
    description: { en: "Take control of a bot's computer.", fr: "Prenez le contrôle de l'ordinateur d'un robot." },
    icon: "MousePointerClick",
    points: 20,
    rule: { kind: "count", event: "computer.control", target: 1 },
    rewards: [skin("bunbu", "chrome")],
  },
  {
    id: "autopilot",
    category: "power",
    name: { en: "Autopilot", fr: "Pilote automatique" },
    description: { en: "Let a bot pick the right computer by itself (Works on: Auto).", fr: "Laissez un robot choisir le bon ordinateur lui-même (Travaille sur : Auto)." },
    icon: "Navigation",
    points: 20,
    rule: { kind: "count", event: "computer.auto", target: 1 },
    rewards: [skin("trombi", "chrome")],
  },
  {
    id: "great-power",
    category: "power",
    name: { en: "With Great Power", fr: "Grands pouvoirs" },
    description: { en: "Grant a bot Full access, then bring it back to Ask.", fr: "Accordez l'Accès complet à un robot, puis ramenez-le à Demander." },
    icon: "Zap",
    points: 50,
    rule: { kind: "all", events: ["fullaccess.granted", "fullaccess.revoked"] },
    rewards: [skin("owl", "holo"), skin("shiba", "holo")],
  },
  {
    id: "palette",
    category: "power",
    name: { en: "Quick Finder", fr: "Trouve-tout" },
    description: { en: "Open the command palette.", fr: "Ouvrez la palette de commandes." },
    icon: "Search",
    points: 5,
    rule: { kind: "count", event: "palette.opened", target: 1 },
    rewards: [{ kind: "appIcon", id: "glyph:cube" }],
  },
  {
    id: "keyboard-ninja",
    category: "power",
    name: { en: "Keyboard Ninja", fr: "Ninja du clavier" },
    description: { en: "Open the keyboard shortcuts.", fr: "Ouvrez les raccourcis clavier." },
    icon: "Keyboard",
    points: 5,
    rule: { kind: "count", event: "shortcuts.opened", target: 1 },
    rewards: [{ kind: "appIcon", id: "glyph:spark" }],
  },

  /* ----------------------------------------------------------------- voice */
  {
    id: "first-call",
    category: "voice",
    name: { en: "On the Line", fr: "En ligne" },
    description: { en: "Call a bot with voice mode.", fr: "Appelez un robot en mode voix." },
    icon: "Phone",
    points: 20,
    rule: { kind: "count", event: "voice.call", target: 1 },
    rewards: [skin("owl", "neon")],
  },
  {
    id: "long-call",
    category: "voice",
    name: { en: "Long Distance", fr: "Interurbain" },
    description: { en: "Stay on a voice call for ten minutes.", fr: "Restez dix minutes en appel vocal." },
    icon: "PhoneCall",
    points: 20,
    rule: { kind: "max", event: "voice.minutes", target: 10 },
    rewards: [skin("bunbu", "crystal")],
  },
  {
    id: "polite-interrupt",
    category: "voice",
    name: { en: "Excuse Me", fr: "Pardon de vous interrompre" },
    description: { en: "Interrupt a bot mid-sentence on a call.", fr: "Interrompez un robot au milieu d'une phrase pendant un appel." },
    icon: "Hand",
    points: 10,
    rule: { kind: "count", event: "voice.interrupt", target: 1 },
    rewards: [title("polite", "Polite", "Poli")],
  },
  {
    id: "hotline",
    category: "voice",
    name: { en: "Hotline", fr: "Ligne directe" },
    description: { en: "Make ten voice calls.", fr: "Faites dix appels vocaux." },
    icon: "PhoneForwarded",
    points: 50,
    rule: { kind: "distinct", event: "voice.call", target: 10 },
    rewards: [skin("bunbu", "holo")],
  },

  /* --------------------------------------------------------- collaboration */
  {
    id: "sharing-is-caring",
    category: "collaboration",
    name: { en: "Sharing Is Caring", fr: "Partager, c'est donner" },
    description: { en: "Share a bot with someone.", fr: "Partagez un robot avec quelqu'un." },
    icon: "Share2",
    points: 20,
    rule: { kind: "count", event: "bot.shared", target: 1 },
    rewards: [skin("shape", "crystal")],
  },
  {
    id: "dream-team",
    category: "collaboration",
    name: { en: "Dream Team", fr: "Équipe de rêve" },
    description: { en: "Talk in a group with another person and two bots.", fr: "Discutez dans un groupe avec une autre personne et deux robots." },
    icon: "UsersRound",
    points: 50,
    rule: { kind: "count", event: "group.mixed", target: 1 },
    rewards: [skin("shape", "galaxy")],
  },
  {
    id: "direct-line",
    category: "collaboration",
    name: { en: "Direct Line", fr: "Message direct" },
    description: { en: "Send a direct message to a colleague.", fr: "Envoyez un message direct à un collègue." },
    icon: "Send",
    points: 10,
    rule: { kind: "count", event: "dm.sent", target: 1 },
    rewards: [title("connector", "Connector", "Rassembleur")],
  },
  {
    id: "group-chat",
    category: "collaboration",
    name: { en: "Round Table", fr: "Table ronde" },
    description: { en: "Send ten messages in groups.", fr: "Envoyez dix messages dans des groupes." },
    icon: "MessageSquareMore",
    points: 10,
    rule: { kind: "count", event: "group.message", target: 10 },
    rewards: [title("host", "Host", "Animateur")],
  },

  /* --------------------------------------------------------------- streaks */
  {
    id: "three-day",
    category: "streaks",
    name: { en: "Warming Up", fr: "On se réchauffe" },
    description: { en: "Use Sagax three days in a row.", fr: "Utilisez Sagax trois jours de suite." },
    icon: "Flame",
    points: 10,
    rule: { kind: "streak", target: 3 },
    rewards: [title("regular", "Regular", "Habitué"), skin("shiba", "retro98")],
  },
  {
    id: "week-streak",
    category: "streaks",
    name: { en: "Week Warrior", fr: "Guerrier de la semaine" },
    description: { en: "Use Sagax seven days in a row.", fr: "Utilisez Sagax sept jours de suite." },
    icon: "CalendarCheck",
    points: 20,
    rule: { kind: "streak", target: 7 },
    rewards: [skin("trombi", "glitch")],
  },
  {
    id: "month-streak",
    category: "streaks",
    name: { en: "Unstoppable", fr: "Inarrêtable" },
    description: { en: "Use Sagax thirty days in a row.", fr: "Utilisez Sagax trente jours de suite." },
    icon: "Rocket",
    points: 100,
    rule: { kind: "streak", target: 30 },
    rewards: [skin("owl", "galaxy")],
  },
  {
    id: "regular",
    category: "streaks",
    name: { en: "Part of the Team", fr: "Membre de l'équipe" },
    description: { en: "Use Sagax on twenty different days.", fr: "Utilisez Sagax vingt jours différents." },
    icon: "CalendarDays",
    points: 50,
    rule: { kind: "activeDays", target: 20 },
    rewards: [skin("bunbu", "molten")],
  },

  /* --------------------------------------------------------------- mastery */
  // Shiba: delegate and let it run.
  {
    ...mastery("hands-off", "routine.clean-streak", 10),
    name: { en: "Hands Off", fr: "Déléguer sans surveiller", ptBR: "Delegar sem vigiar" },
    description: {
      en: "One of your routines completes 10 runs in a row without a failure.",
      fr: "Une de vos routines complète 10 exécutions de suite sans un seul échec.",
      ptBR: "Uma das suas rotinas completa 10 execuções seguidas sem nenhuma falha.",
    },
    icon: "Dog",
    points: 100,
  },
  {
    ...mastery("second-wind", "routine.recovered", 2),
    name: { en: "Second Wind", fr: "Second souffle", ptBR: "Segundo fôlego" },
    description: {
      en: "Twice, fix a routine that failed: change it, then see its next 3 runs complete.",
      fr: "Deux fois, réparez une routine qui a échoué : modifiez-la, puis voyez ses 3 exécutions suivantes réussir.",
      ptBR: "Duas vezes, conserte uma rotina que falhou: altere-a e veja as 3 execuções seguintes concluírem.",
    },
    icon: "LifeBuoy",
    points: 100,
  },
  {
    ...mastery("common-thread", "routine.continuity-runs", 14),
    name: { en: "Common Thread", fr: "Fil conducteur", ptBR: "Fio condutor" },
    description: {
      en: "A routine that builds on its previous report completes 14 runs.",
      fr: "Une routine qui reprend son rapport précédent complète 14 exécutions.",
      ptBR: "Uma rotina que parte do relatório anterior completa 14 execuções.",
    },
    icon: "Repeat2",
    points: 150,
  },
  {
    ...mastery("quiet-nights", "routine.quiet-days", 30),
    name: { en: "Quiet Nights", fr: "Nuit calme", ptBR: "Noites tranquilas" },
    description: {
      en: "30 days in a row where your routines ran and none failed.",
      fr: "30 jours de suite où vos routines ont roulé sans un seul échec.",
      ptBR: "30 dias seguidos em que suas rotinas rodaram sem nenhuma falha.",
    },
    icon: "MoonStar",
    points: 150,
  },
  {
    ...mastery("pack-leader", "routine.pack", 3),
    name: { en: "Pack Leader", fr: "Chef de meute", ptBR: "Líder da matilha" },
    description: {
      en: "Routines on 3 different bots each complete 20 runs.",
      fr: "Des routines sur 3 robots différents complètent chacune 20 exécutions.",
      ptBR: "Rotinas em 3 robôs diferentes completam 20 execuções cada.",
    },
    icon: "Workflow",
    points: 200,
  },
  // Grump: read before you trust.
  {
    ...mastery("reviewer", "approval.denied-then-done", 5),
    name: { en: "Reviewer", fr: "Relecteur", ptBR: "Revisor" },
    description: {
      en: "Deny 5 approvals that would have written to a system, and each time the bot still completes the task another way.",
      fr: "Refusez 5 approbations qui auraient écrit dans un système, et chaque fois le robot termine quand même la tâche autrement.",
      ptBR: "Negue 5 aprovações que teriam escrito em um sistema e, a cada vez, o robô conclui a tarefa de outro jeito.",
    },
    icon: "ThumbsDown",
    points: 100,
  },
  {
    ...mastery("prompter", "turn.steered-then-done", 15),
    name: { en: "Prompter", fr: "Souffleur", ptBR: "Ponto" },
    description: {
      en: "15 times, correct a bot while it works (a message into its running turn) and the turn completes.",
      fr: "15 fois, corrigez un robot pendant qu'il travaille (un message dans son tour en cours) et le tour se termine bien.",
      ptBR: "15 vezes, corrija um robô enquanto ele trabalha (uma mensagem no turno em andamento) e o turno conclui.",
    },
    icon: "MessageSquareWarning",
    points: 100,
  },
  {
    ...mastery("red-pen", "persona.revised", 5),
    name: { en: "Red Pen", fr: "Stylo rouge", ptBR: "Caneta vermelha" },
    description: {
      en: "On 5 different days, revise a bot's standing instructions and see it complete 5 turns with them.",
      fr: "5 jours différents, révisez les instructions permanentes d'un robot et voyez-le compléter 5 tours avec elles.",
      ptBR: "Em 5 dias diferentes, revise as instruções permanentes de um robô e veja-o concluir 5 turnos com elas.",
    },
    icon: "PenLine",
    points: 150,
  },
  {
    ...mastery("not-so-fast", "turn.stopped-then-done", 10),
    name: { en: "Not So Fast", fr: "Pas si vite", ptBR: "Calma lá" },
    description: {
      en: "Stop a bot 10 times, and each time its next turn completes.",
      fr: "Arrêtez un robot 10 fois, et chaque fois son tour suivant se termine bien.",
      ptBR: "Pare um robô 10 vezes e, a cada vez, o turno seguinte conclui.",
    },
    icon: "OctagonPause",
    points: 150,
    hidden: true,
    hint: {
      en: "Sometimes the best move is the stop button, then a better ask.",
      fr: "Parfois, le meilleur coup est le bouton Arrêter, puis une meilleure demande.",
      ptBR: "Às vezes, o melhor lance é o botão Parar e depois um pedido melhor.",
    },
  },
  {
    ...mastery("justice-of-peace", "approval.judgment", 20),
    name: { en: "Justice of the Peace", fr: "Juge de paix", ptBR: "Juiz de paz" },
    description: {
      en: "Answer 100 approvals, at least 20 of them denials.",
      fr: "Répondez à 100 approbations, dont au moins 20 refus.",
      ptBR: "Responda 100 aprovações, com pelo menos 20 negativas.",
    },
    icon: "Gavel",
    points: 200,
  },
  // Ogre: carry the heavy work.
  {
    ...mastery("conductor", "delegation.conducted", 3),
    name: { en: "Conductor", fr: "Chef d'orchestre", ptBR: "Maestro" },
    description: {
      en: "3 times, a bot hands work to two other bots, both come back done, and its turn completes.",
      fr: "3 fois, un robot confie du travail à deux autres robots, les deux reviennent avec le travail fait, et son tour se termine bien.",
      ptBR: "3 vezes, um robô passa trabalho a dois outros robôs, os dois voltam com tudo feito e o turno conclui.",
    },
    icon: "Waypoints",
    points: 100,
  },
  {
    ...mastery("ten-hands", "threads.tidy", 10),
    name: { en: "Ten Hands", fr: "Dix mains", ptBR: "Dez mãos" },
    description: {
      en: "10 open conversations in 5 folders, and none left untouched for 30 days.",
      fr: "10 conversations ouvertes dans 5 dossiers, et aucune laissée sans activité depuis 30 jours.",
      ptBR: "10 conversas abertas em 5 pastas, e nenhuma parada há 30 dias.",
    },
    icon: "FolderTree",
    points: 100,
  },
  {
    ...mastery("plugged-in", "integrations.week", 3),
    name: { en: "Plugged In", fr: "Branché", ptBR: "Conectado" },
    description: {
      en: "Your bots use tools from 3 different integrations within one week.",
      fr: "Vos robots utilisent les outils de 3 intégrations différentes en une semaine.",
      ptBR: "Seus robôs usam ferramentas de 3 integrações diferentes em uma semana.",
    },
    icon: "PlugZap",
    points: 150,
  },
  {
    ...mastery("swarm", "subagents.turn", 3),
    name: { en: "Swarm", fr: "Essaim", ptBR: "Enxame" },
    description: {
      en: "One turn puts 3 sub-agents to work and completes.",
      fr: "Un seul tour met 3 sous-agents au travail et se termine bien.",
      ptBR: "Um único turno põe 3 subagentes para trabalhar e conclui.",
    },
    icon: "Boxes",
    points: 150,
  },
  {
    ...mastery("full-house", "bots.concurrent", 3),
    name: { en: "Full House", fr: "Salle comble", ptBR: "Casa cheia" },
    description: {
      en: "3 of your bots work at the same time, and all of them finish well.",
      fr: "3 de vos robots travaillent en même temps, et tous terminent bien.",
      ptBR: "3 dos seus robôs trabalham ao mesmo tempo e todos terminam bem.",
    },
    icon: "Orbit",
    points: 200,
  },
  // Frog: know your models and your knowledge.
  {
    ...mastery("polyglot", "providers.thread", 3),
    name: { en: "Polyglot", fr: "Polyglotte", ptBR: "Poliglota" },
    description: {
      en: "Run one conversation on models from 3 different providers.",
      fr: "Faites rouler une même conversation sur des modèles de 3 fournisseurs différents.",
      ptBR: "Rode uma mesma conversa em modelos de 3 provedores diferentes.",
    },
    icon: "GitCompare",
    points: 100,
  },
  {
    ...mastery("thrifty", "auto.thrifty-weeks", 1),
    name: { en: "Thrifty", fr: "Économe", ptBR: "Econômico" },
    description: {
      en: "In one week of at least 20 Auto turns, Auto picks a cheaper model than the bot's own for more than half.",
      fr: "Sur une semaine d'au moins 20 tours en Auto, Auto choisit un modèle moins cher que celui du robot pour plus de la moitié.",
      ptBR: "Em uma semana com pelo menos 20 turnos em Auto, o Auto escolhe um modelo mais barato que o do robô em mais da metade.",
    },
    icon: "PiggyBank",
    points: 100,
  },
  {
    ...mastery("translator", "french.threads", 5),
    name: { en: "Translator", fr: "Traducteur", ptBR: "Tradutor" },
    description: {
      en: "5 conversations of at least 6 turns entirely in French: your messages and the bot's answers.",
      fr: "5 conversations d'au moins 6 tours entièrement en français : vos messages et les réponses du robot.",
      ptBR: "5 conversas de pelo menos 6 turnos inteiramente em francês: suas mensagens e as respostas do robô.",
    },
    icon: "Languages",
    points: 150,
  },
  {
    ...mastery("skill-smith", "skills.learned-uses", 20),
    name: { en: "Skill Smith", fr: "Forgeron de skills", ptBR: "Ferreiro de skills" },
    description: {
      en: "A skill a bot wrote from one of your conversations (/learn) is used in 20 turns.",
      fr: "Une skill qu'un robot a écrite à partir d'une de vos conversations (/learn) sert dans 20 tours.",
      ptBR: "Uma skill que um robô escreveu a partir de uma conversa sua (/learn) é usada em 20 turnos.",
    },
    icon: "BookOpenCheck",
    points: 150,
  },
  {
    ...mastery("total-recall", "memory.recall-threads", 10),
    name: { en: "Total Recall", fr: "Mémoire vive", ptBR: "Memória viva" },
    description: {
      en: "Write a bot's memory yourself, then see it recalled in 10 different conversations.",
      fr: "Écrivez vous-même la mémoire d'un robot, puis voyez-la rappelée dans 10 conversations différentes.",
      ptBR: "Escreva você mesmo a memória de um robô e veja-a lembrada em 10 conversas diferentes.",
    },
    icon: "BrainCircuit",
    points: 200,
  },
  // The four hardest: the premium skins of every Mastery character.
  {
    ...mastery("ferryman", "catalog.imports", 3),
    name: { en: "Ferryman", fr: "Passeur", ptBR: "Barqueiro" },
    description: {
      en: "Publish a bot to your organization's catalogue, and 3 people import it.",
      fr: "Publiez un robot dans le catalogue de votre organisation, et 3 personnes l'importent.",
      ptBR: "Publique um robô no catálogo da sua organização e 3 pessoas o importam.",
    },
    icon: "Ship",
    points: 250,
  },
  {
    ...mastery("second-opinion", "delegation.cross-model", 10),
    name: { en: "Second Opinion", fr: "Deuxième avis", ptBR: "Segunda opinião" },
    description: {
      en: "10 times, a bot hands work to a bot on another model family and it comes back done.",
      fr: "10 fois, un robot confie du travail à un robot d'une autre famille de modèles, et il revient avec le travail fait.",
      ptBR: "10 vezes, um robô passa trabalho a um robô de outra família de modelos e ele volta com tudo feito.",
    },
    icon: "Scale",
    points: 250,
    hidden: true,
    hint: {
      en: "Two models see more than one.",
      fr: "Deux modèles voient plus qu'un seul.",
      ptBR: "Dois modelos veem mais do que um.",
    },
  },
  {
    ...mastery("clean-slate", "approvals.clean-days", 20),
    name: { en: "Clean Slate", fr: "Table rase", ptBR: "Tudo em dia" },
    description: {
      en: "20 days where every approval asked of you was answered the same day and none of your routines failed.",
      fr: "20 jours où chaque approbation demandée a reçu sa réponse le jour même et où aucune de vos routines n'a échoué.",
      ptBR: "20 dias em que toda aprovação pedida a você foi respondida no mesmo dia e nenhuma rotina sua falhou.",
    },
    icon: "Eraser",
    points: 250,
  },
  {
    id: "sagax-master",
    category: "mastery",
    name: { en: "Sagax Master", fr: "Sagax accompli", ptBR: "Mestre Sagax" },
    description: {
      en: "Unlock 20 other Mastery achievements.",
      fr: "Débloquez 20 autres succès de Maîtrise.",
      ptBR: "Desbloqueie 20 outras conquistas de Maestria.",
    },
    icon: "GraduationCap",
    points: 300,
    rule: { kind: "category", category: "mastery", target: 20 },
    rewards: [...(masteryRewards("sagax-master") as AchievementReward[]), title("sage", "Sagax Master", "Sagax accompli")],
  },

  /* ----------------------------------------------------------------- tiers */
  {
    id: "bronze",
    category: "tiers",
    name: { en: "Bronze", fr: "Bronze" },
    description: { en: "Earn 100 points.", fr: "Obtenez 100 points." },
    icon: "Medal",
    points: 10,
    rule: { kind: "points", target: 100 },
    rewards: [title("bronze", "Bronze Operator", "Opérateur bronze")],
  },
  {
    id: "silver",
    category: "tiers",
    name: { en: "Silver", fr: "Argent" },
    description: { en: "Earn 300 points.", fr: "Obtenez 300 points." },
    icon: "Award",
    points: 20,
    rule: { kind: "points", target: 300 },
    rewards: [title("silver", "Silver Operator", "Opérateur argent"), skin("shiba", "glitch")],
  },
  {
    id: "gold-tier",
    category: "tiers",
    name: { en: "Gold", fr: "Or" },
    description: { en: "Earn 600 points.", fr: "Obtenez 600 points." },
    icon: "Trophy",
    points: 50,
    rule: { kind: "points", target: 600 },
    rewards: [skin("trombi", "holo")],
  },
  {
    id: "platinum",
    category: "tiers",
    name: { en: "Platinum", fr: "Platine" },
    description: { en: "Unlock every achievement that is not a secret, Mastery aside.", fr: "Débloquez tous les succès qui ne sont pas secrets, hors Maîtrise." },
    icon: "Gem",
    points: 100,
    rule: { kind: "completion" },
    rewards: [skin("bunbu", "galaxy"), title("platinum", "Platinum Sage", "Sage platine")],
  },

  /* --------------------------------------------------------------- secrets */
  {
    id: "trombi-summoned",
    category: "secrets",
    name: { en: "It Looks Like You're Writing", fr: "On dirait que vous écrivez" },
    description: { en: "Summon Trombi with its command. Trombi is yours for good.", fr: "Invoquez Trombi avec sa commande. Trombi est à vous pour de bon." },
    icon: "Paperclip",
    points: 20,
    hidden: true,
    hint: { en: "A retro command, typed alone in the composer, brings back an old office friend.", fr: "Une commande rétro, tapée seule dans la zone de saisie, ramène un vieil ami de bureau." },
    rule: { kind: "count", event: "trombi.summoned", target: 1 },
    rewards: [{ kind: "character", character: "trombi" }],
  },
  {
    id: "konami",
    category: "secrets",
    name: { en: "Up Up Down Down", fr: "Haut haut bas bas" },
    description: { en: "Enter the old cheat code.", fr: "Entrez le vieux code de triche." },
    icon: "Gamepad2",
    points: 50,
    hidden: true,
    hint: { en: "Gamers of a certain age know a code made of arrows.", fr: "Les joueurs d'une certaine époque connaissent un code fait de flèches." },
    rule: { kind: "count", event: "konami", target: 1 },
    rewards: [skin("owl", "lightning")],
  },
  {
    id: "night-owl",
    category: "secrets",
    name: { en: "Night Owl", fr: "Oiseau de nuit" },
    description: { en: "Talk to your desktop mascot between midnight and 1 a.m.", fr: "Parlez à votre mascotte de bureau entre minuit et 1 h." },
    icon: "Moon",
    points: 50,
    hidden: true,
    hint: { en: "Owls are at their best after midnight.", fr: "Les hiboux sont à leur meilleur après minuit." },
    rule: { kind: "count", event: "mascot.midnight", target: 1 },
    rewards: [skin("owl", "spirit")],
  },
  {
    id: "good-bot",
    category: "secrets",
    name: { en: "Who's a Good Bot?", fr: "Qui est un bon robot?" },
    description: { en: "Pet your mascot fifty times.", fr: "Flattez votre mascotte cinquante fois." },
    icon: "Heart",
    points: 10,
    hidden: true,
    hint: { en: "Your mascot loves a little affection.", fr: "Votre mascotte adore un peu d'affection." },
    rule: { kind: "count", event: "mascot.pet", target: 50 },
    rewards: [title("petter", "Bot Whisperer", "Charmeur de robots")],
  },
  {
    id: "best-friends",
    category: "secrets",
    name: { en: "Best Friends Forever", fr: "Meilleurs amis pour la vie" },
    description: { en: "Pet your mascot five hundred times.", fr: "Flattez votre mascotte cinq cents fois." },
    icon: "HeartHandshake",
    points: 50,
    hidden: true,
    hint: { en: "Lots and lots of affection.", fr: "Beaucoup, beaucoup d'affection." },
    rule: { kind: "count", event: "mascot.pet", target: 500 },
    rewards: [skin("trombi", "molten")],
  },
  {
    id: "desk-buddy",
    category: "secrets",
    name: { en: "Desk Buddy", fr: "Copain de bureau" },
    description: { en: "Put a bot on your desktop.", fr: "Mettez un robot sur votre bureau." },
    icon: "Monitor",
    points: 10,
    rule: { kind: "count", event: "mascot.floated", target: 1 },
    rewards: [title("buddy", "Desk Buddy", "Copain de bureau"), { kind: "character", character: "shiba" }],
  },
  {
    id: "trophy-case",
    category: "secrets",
    name: { en: "Trophy Case", fr: "Vitrine à trophées" },
    description: { en: "Admire your achievements.", fr: "Admirez vos succès." },
    icon: "Trophy",
    points: 5,
    hidden: true,
    hint: { en: "Take a look at your trophies.", fr: "Jetez un œil à vos trophées." },
    rule: { kind: "count", event: "achievements.viewed", target: 1 },
    rewards: [title("collector", "Collector", "Collectionneur")],
  },
  {
    id: "icon-swap",
    category: "secrets",
    name: { en: "New Look, Who Dis?", fr: "Nouvelle tête" },
    description: { en: "Change the app's icon.", fr: "Changez l'icône de l'application." },
    icon: "AppWindow",
    points: 10,
    hidden: true,
    hint: { en: "The Dock could use a new face.", fr: "Le Dock aurait bien besoin d'une nouvelle tête." },
    rule: { kind: "count", event: "appicon.changed", target: 1 },
    rewards: [title("stylist", "Stylist", "Styliste")],
  },
];

/**
 * Every Mastery achievement also gives its own title (its name), so a rung
 * whose character has not registered its named skins yet still rewards
 * something, and the Mastery titles show off the hard part of the work.
 */
export const ACHIEVEMENTS: readonly AchievementDefinition[] = CATALOG.map((item) =>
  item.category === "mastery" && !item.rewards.some((reward) => reward.kind === "title")
    ? { ...item, rewards: [...item.rewards, { kind: "title", id: item.id, name: { en: item.name.en, fr: item.name.fr, ...(item.name.ptBR ? { ptBR: item.name.ptBR } : {}) } }] }
    : item,
);

const byId = new Map(ACHIEVEMENTS.map((item) => [item.id, item]));

export function achievementById(id: string): AchievementDefinition | undefined {
  return byId.get(id);
}
