// Writes electron/local-vm-recipe.mjs: the Local VM recipe (pinned image,
// Dockerfile, hardened `run` arguments) that the desktop app uses when a bot
// creates the Local VM on the person's PC through the desktop bridge (server
// mode, where no local server runs). The one source of truth stays
// server/container-computer.ts; server/local-vm-recipe.test.ts fails when the
// generated file drifts from it.
//
//   node --experimental-strip-types scripts/gen-local-vm-recipe.ts
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  BASE_IMAGE, BASE_IMAGE_DIGEST, BASE_IMAGE_LABEL, CONTAINER, CUA_DRIVER_VERSION, CUA_SOCKET, DRIVER_LABEL, IMAGE,
  IMAGE_LAYER_LABEL, IMAGE_LAYER_VERSION, MANAGED_LABEL, SHARED_LOCAL_VM_TARGET, containerRunArgs, managedImageDockerfile,
} from "../server/container-computer.ts";

const PASSWORD = "{{SAGAX_VNC_PASSWORD}}";
const WORKSPACE = "{{SAGAX_VM_WORKSPACE}}";

export function localVmRecipeSource(): string {
  const target = { ...SHARED_LOCAL_VM_TARGET, workspaceDir: WORKSPACE };
  const template = (runtime: "docker" | "podman") => containerRunArgs(runtime, PASSWORD, target);
  const json = (value: unknown) => JSON.stringify(value, null, 2);
  return `// GENERATED by scripts/gen-local-vm-recipe.ts from server/container-computer.ts.
// Do not edit; run the script again. server/local-vm-recipe.test.ts checks it.
export const CONTAINER = ${json(CONTAINER)};
export const IMAGE = ${json(IMAGE)};
export const BASE_IMAGE = ${json(BASE_IMAGE)};
export const CUA_SOCKET = ${json(CUA_SOCKET)};
export const MANAGED_LABEL = ${json(MANAGED_LABEL)};
/** The labels a usable desktop image carries (imageLabelsMatch). */
export const IMAGE_LABELS = ${json({ [MANAGED_LABEL]: "1", [DRIVER_LABEL]: CUA_DRIVER_VERSION, [BASE_IMAGE_LABEL]: BASE_IMAGE_DIGEST, [IMAGE_LAYER_LABEL]: IMAGE_LAYER_VERSION })};
export const DOCKERFILE = ${json(managedImageDockerfile())};
const RUN_ARGS = ${json({ docker: template("docker"), podman: template("podman") })};
const PASSWORD = ${json(PASSWORD)};
const WORKSPACE = ${json(WORKSPACE)};

/** \`<runtime> run\` arguments for the shared Local VM (containerRunArgs). */
export function runArgs(runtime, password, workspaceDir) {
  const args = RUN_ARGS[runtime];
  if (!args) throw new Error("Docker or Podman is required to create the Local VM here");
  return args.map(arg => arg.split(PASSWORD).join(password).split(WORKSPACE).join(workspaceDir));
}
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const out = join(dirname(fileURLToPath(import.meta.url)), "..", "electron", "local-vm-recipe.mjs");
  writeFileSync(out, localVmRecipeSource());
  console.log(`wrote ${out}`);
}
