#!/usr/bin/env node
// Writes ios/Sources/CompanionCore/AchievementCatalog.swift from the
// desktop's catalog (shared/achievements-catalog.ts), the one source of the
// names, descriptions, hints, icons, points and rewards: the server sends
// only each achievement's state (GET /api/me/achievements). Reward names
// (characters, skins) come from the renderer's locale files, as
// src/lib/achievements.ts `rewardLabel` reads them.
//
//   node ios/parity/achievements-catalog.mjs        # rewrite the Swift file
//   node ios/parity/achievements-catalog.mjs --check # fail when it is stale
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..", "..");
const OUT = join(ROOT, "ios", "Sources", "CompanionCore", "AchievementCatalog.swift");
const { ACHIEVEMENTS } = await import(join(ROOT, "shared", "achievements-catalog.ts"));
const locale = (name) => JSON.parse(readFileSync(join(ROOT, "src", "locales", `${name}.json`), "utf8"));
const LOCALES = { en: locale("en"), fr: locale("fr"), ptBR: locale("pt-br") };

const CHARACTER_KEY = { owl: "floatingBots.mascot.owl", shape: "floatingBots.mascot.body", trombi: "floatingBots.mascot.trombi", bunbu: "floatingBots.mascot.bunbu" };
const skinKey = (character, skin) => character === "owl"
  ? `mascot.skin.${skin === "none" ? "classic" : skin}`
  : `mascot.${character === "shape" ? "shapeSkin" : `${character}Skin`}.${skin}`;
const pick = (key) => {
  const en = LOCALES.en[key];
  if (en === undefined) throw new Error(`missing locale key ${key}`);
  return { en, fr: LOCALES.fr[key] ?? en, ptBR: LOCALES.ptBR[key] ?? en };
};
const s = (text) => JSON.stringify(text);
const text = (t) => (t ? `AchievementText(en: ${s(t.en)}, fr: ${s(t.fr ?? t.en)}, ptBR: ${s(t.ptBR ?? t.en)})` : "nil");

function reward(r) {
  switch (r.kind) {
    case "character": return `.character(id: ${s(r.character)}, name: ${text(pick(CHARACTER_KEY[r.character]))})`;
    case "skin": return `.skin(character: ${s(r.character)}, skin: ${s(r.skin)}, name: ${text(pick(skinKey(r.character, r.skin)))}, characterName: ${text(pick(CHARACTER_KEY[r.character]))})`;
    case "appIcon": return `.appIcon(id: ${s(r.id)})`;
    case "title": return `.title(id: ${s(r.id)}, name: ${text(r.name)})`;
    default: throw new Error(`unknown reward ${r.kind}`);
  }
}

const entries = ACHIEVEMENTS.map((a) => [
  "        AchievementDefinition(",
  `            id: ${s(a.id)}, category: .${a.category}, icon: ${s(a.icon)}, points: ${a.points}, hidden: ${a.hidden === true},`,
  `            name: ${text(a.name)},`,
  `            description: ${text(a.description)},`,
  `            hint: ${text(a.hint)},`,
  `            rewards: [${(a.rewards ?? []).map(reward).join(", ")}]`,
  "        ),",
].join("\n"));

const swift = `// Generated by ios/parity/achievements-catalog.mjs from
// shared/achievements-catalog.ts and src/locales: do not edit by hand.
// The catalog has English and French; Portuguese falls back to English
// except for the reward names, which the renderer's locales carry.
import Foundation

public extension AchievementDefinition {
    static let catalog: [AchievementDefinition] = [
${entries.join("\n")}
    ]
}
`;

if (process.argv.includes("--check")) {
  if (readFileSync(OUT, "utf8") !== swift) { console.error("AchievementCatalog.swift is stale: run node ios/parity/achievements-catalog.mjs"); process.exit(1); }
} else {
  writeFileSync(OUT, swift);
  console.log(`${ACHIEVEMENTS.length} achievements -> ${OUT}`);
}
